### ISSUE TITLE
Firebase Crashalytics -[OSInAppMessageViewController loadMessageContent]

### ISSUE THREAD

**Issue by seyhunak** [OneSignal/OneSignal-iOS-SDK#1032] opened 2021-12-15 06:51 UTC
Crashalytics -[OSInAppMessageViewController loadMessageContent] crashing suddenly.  
Any update for the issue?

**Description:**
3.16.0 (243)
iOS 15.2.0
iPhone 11 Pro Max
Dec 15, 2021, 10:35:06 AM

**Environment**

**Steps to Reproduce Issue:**
  - New in-app from OneSignal message appears
  - Onesignal handles the message
  - Application crashed suddenly.

Stack Trace:

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x990fc __exceptionPreprocess
1  libobjc.A.dylib                0x15d64 objc_exception_throw
2  CoreFoundation                 0x1a2564 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1ad6e0 -[__NSPlaceholderDictionary initWithCapacity:].cold.1
4  CoreFoundation                 0x56514 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x74ebc +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  IBAMobileBankNetwork           0xf2a84 (Missing)
7  IBAMobileBankNetwork           0xb02fc (Missing)
8  ABB Mobile                     0x1c40e28 -[OSInAppMessageViewController loadMessageContent]
9  ABB Mobile                     0x1c3ff28 -[OSInAppMessageViewController viewDidLoad]
10 UIKitCore                      0x1ad944 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]
11 UIKitCore                      0x1b03f8 -[UIViewController loadViewIfRequired]
12 UIKitCore                      0x182f14 -[UIViewController view]
13 ABB Mobile                     0x1c09294 __37-[OSMessagingController showMessage:]_block_invoke
14 libdispatch.dylib              0x2924 _dispatch_call_block_and_release
15 libdispatch.dylib              0x4670 _dispatch_client_callout
16 libdispatch.dylib              0x12b70 _dispatch_main_queue_callback_4CF
17 CoreFoundation                 0x51d84 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
18 CoreFoundation                 0xbf5c __CFRunLoopRun
19 CoreFoundation                 0x1f468 CFRunLoopRunSpecific
20 GraphicsServices               0x138c GSEventRunModal
21 UIKitCore                      0x51a088 -[UIApplication _run]
22 UIKitCore                      0x298958 UIApplicationMain
23 ABB Mobile                     0x79e8 main + 38 (AppDelegate.swift:38)
24 ???                            0x106ea9aa4 (Missing)


```

**Comment by emawby** [comment] 2022-01-10 22:03
@seyhunak Thank you for reaching out. Are you able to reproduce this issue? It looks like this might either be a memory issue, or something is causing appId to be nil. When are you calling `setAppId`?

**Comment by SigniOS** [comment] 2022-02-18 02:14
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by emawby** [comment] 2022-02-28 20:03
Closing for now. Please feel free to reopen if this is still an issue

**Closed by emawby** 2022-02-28 20:03 UTC
Labels: Need More Information
