### ISSUE TITLE
AppStore rejections for NSLocationWhenInUseUsageDescription

### ISSUE THREAD

**Issue by peterpaulis** [OneSignal/OneSignal-iOS-SDK#368] opened 2018-04-26 14:35 UTC
**Description:**
I cannot upload my app to appstore as i get 

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.

**The app was previously working and approved, this was an minor minor update**

**My app doesnt use location!**

**Environment**
Latest XCode 9.3

**Steps to Reproduce Issue:**
1. submit app using onesignal to appstore
2. you ge immidietly rejected

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by LKDevelopment** [comment] 2018-04-26 14:44
See https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/363 for this.

**Comment by gdeglin** [comment] 2018-04-26 15:48
Thanks for reporting this. Our team is investigating.

**Comment by uncleho** [comment] 2018-04-26 16:47
It's an issue happening to a lot of people on the developer forums, not sure if it's OneSignal related: https://forums.developer.apple.com/thread/101367

**Comment by Nightsd01** [comment] 2018-04-26 18:31
@peterpaulis Can you try something as a debugging step? Can you try removing the OneSignal SDK from your project and see if that resolves the issue?

We're trying to reproduce this issue on our side, we've got some test apps, but our apps are not getting denied.

**Comment by Nightsd01** [comment] 2018-04-26 19:07
@habovh This seems to be happening to a lot of people, many of them don't use the OneSignal SDK in their app, so we don't think this issue is related to OneSignal.

`NSLocationAlwaysUsageDescription` is _not_ mandatory with the OneSignal SDK. It will work just fine if you only use `NSLocationWhenInUsageDescription`. The problem seems to have been an issue with Apple's review system, and it seems they are rolling out a fix. We will continue to keep investigating the problem.

In the mean time, can you try completely removing the OneSignal SDK from your project and see if Apple will accept a new build? You don't need to submit it for review, we just want to isolate the issue.

**Comment by Nightsd01** [comment] 2018-04-26 19:07
Ok, I can confirm that Apple is aware of this issue and their engineers are looking into it.

**Comment by OmarShoaib** [comment] 2018-08-31 06:16
Thanks for quick reply @Nightsd01

BTW I forgot to tell you that I am using UnitySDK of OneSignal and the dependencies/plugins besides OneSignal that I am using are listed below

Vuforia
Sqlite3
NativeGallery
UnityOBBDownloader (User PlayServices)

They all are working fine until the last update.

**Comment by keithdmoore** [comment] 2018-09-01 00:06
I just started getting this message as well.

**Comment by Nightsd01** [comment] 2018-09-01 03:03
@OmarShoaib that is interesting, this issue used to be extremely rare, Apple may have changed things. We will look into this issue.

**Comment by EthanCG** [comment] 2018-09-02 17:13
Hi, just happening to me.
I'm using ionic, below version info 
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v6.11.2
    npm   : 3.10.10 
    OS    : macOS High Sierra
    Xcode : Xcode 9.4.1 Build version 9F2000 
`
Plugin depencies 
`cordova-plugin-device 2.0.2 "Device"
cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"`

I have other apps with same depencies except OneSignal and I haven't store rejection.

**Comment by EthanCG** [comment] 2018-09-03 10:42
Then after many tests, I removed OneSignal for compatibility issue with YouTubePlayer plugin and replace it by another notification plugin. Same issue with this second notification provider. The only way to solve the Apple mail issu is to add key to the info.plist like this : 
`
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Send Geolocated notifications</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Send Geolocated notifications</string>
`
Adding entry in the config.xml doesn't make required update to the info.plist file.

**Comment by kaasasolut** [comment] 2018-09-03 11:31
I think it's because of Unity itself. We do not use this SDK but got the same message from App Store Connect just moments ago.
Unity includes a file called `iPhone_Sensors.mm`. In that, there's the following code:
```objectivec
void LocationService::StartUpdatingLocation()
{
    if (gLocationServiceStatus.locationStatus != kLocationServiceRunning)
    {
        CLLocationManager* locationManager = gLocationServiceStatus.GetLocationManager();

        // request authorization on ios8
        if ([locationManager respondsToSelector: @selector(requestWhenInUseAuthorization)])
            [locationManager performSelector: @selector(requestWhenInUseAuthorization)];

        locationManager.desiredAccuracy = gLocationServiceStatus.desiredAccuracy;
        // Set a movement threshold for new events
        locationManager.distanceFilter = gLocationServiceStatus.distanceFilter;

#if PLATFORM_IOS
        [locationManager startUpdatingLocation];
#else
        [locationManager requestLocation];
#endif

        gLocationServiceStatus.locationStatus = kLocationServiceInitializing;
    }
}
```
The [documentation for requestWhenInUseAuthorization](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620562-requestwheninuseauthorization?language=objc) says:
> When the current authorization status is [`kCLAuthorizationStatusNotDetermined`](https://developer.apple.com/documentation/corelocation/clauthorizationstatus/kclauthorizationstatusnotdetermined?language=objc), this method runs asynchronously and prompts the user to grant permission to the app to use location services. The user prompt contains the text from the `NSLocationWhenInUseUsageDescription` key in your app’s `Info.plist` file, and the presence of that key is required when calling this method.

It seems that Apple changed something in their processing, so that triggers the message now.

**Comment by Nightsd01** [comment] 2018-09-03 22:26
Thanks for the helpful info. It looks like Apple is simply scanning the bitcode for any usage of location services. Our SDK accesses location services indirectly to avoid a crash if an app doesn’t use location services, so they must be scanning strings too....

It’s a bit ridiculous considering how many dependencies/frameworks use location services but only under certain conditions that may not be applicable to some apps. 

I’ll keep this issue open until we’ve found a solution. 

As a temporary workaround, if you don’t use location-based push notifications, you can call `OneSignal.setLocationShared(false)`. That will turn off location access from our SDK. If you add the location permissions to your info.plist, Apple will stop sending you those warnings, but as long as your app never requests location permission, the plist strings will go unused.

**Comment by OmarShoaib** [comment] 2018-09-07 06:28
Thumbs up! @EthanCG and @Nightsd01 

For now, I've just added both OneSignal.SetLocationShared(false) and NSLocation permission strings and uploaded the binary. Voila! No error emails. And there's no popup of location permission in the app as well. So, that might be a possible workaround at the time.

Thanks all

**Comment by keithdmoore** [comment] 2018-09-07 06:40
Without making any changes, I did not get any emails from Apple today after pushing a build to the App Store.

**Comment by Nightsd01** [comment] 2018-09-28 00:12
We have heard that this was a bug with Apple's static analysis for new build uploads and was fixed - we have not heard any additional complaints so I'll be closing this issue.

If anyone sees an email like this in the future **please** post here.

**Closed by Nightsd01** 2018-09-28 00:12 UTC

**Comment by VitorGit** [comment] 2019-03-28 11:52
Just received this exact same email. No new plugins were added and the previous builds were accepted just fine.

**Comment by gnoph** [comment] 2019-03-28 14:48
We got the same email today too. Not sure if it's another one-time deal or Apple really believes that we are using location APIs. I searched the xcode project generated by Unity's iOS build for "NSLocation" and I found only libOneSignal.a having a match.

**Comment by jkasten2** [comment] 2019-03-28 21:09
@VitorGit Can you check if you have the Core Location library in your Xcode project. If so can your remove it?

@gnoph Thanks for all the details. If you remove the Core Location library from the generated project do you get compile errors with `iPhone_Sensors.mm`? I would assume so but it is possible there are preprocessors handling this.

**Comment by gnoph** [comment] 2019-03-28 21:33
Hi, @jkasten2.

Thanks for the hint. I just realized that the CoreLocation usages from iPhone_Sensors.mm are conditional on UNITY_USES_LOCATION preprocessor macro, which is currently defined to 0 in our project. That is, our app does not depend on CoreLocation framework. The framework is included in the project but not tagged with any targets. Removing it from the project does not affect the build. I haven't tried App Store submission yet.

Now I think our app does not have explicit references of CoreLocation APIs in the binary at all. I guess Apple somehow detected it in OneSignal library, even though it's used indirectly.

> 
> 
> @VitorGit Can you check if you have the Core Location library in your Xcode project. If so can your remove it?
> 
> @gnoph Thanks for all the details. If you remove the Core Location library from the generated project do you get compile errors with `iPhone_Sensors.mm`? I would assume so but it is possible there are preprocessors handling this.

**Comment by jkasten2** [comment] 2019-03-28 23:06
@gnoph Good to hear that removing the library still lets you build. It might be that Apple detects it's use at runtime when evaluating the app so removing Core Location means that OneSignal won't even try to check permission. The might be doing some static analysis though, it's hard to say.

Keep us updated on what your latest submission results in.

**Comment by JEKos** [comment] 2019-03-29 01:04
Same problem here, email says

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "MY APP NAME". Please correct the following issues, then upload again.
> 
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."
> 
> Best regards,
> 
> The App Store Team

Is it a bug from Apple? What we suppose to do with that?

**Comment by Nightsd01** [comment] 2019-03-29 01:09
Parts of the OneSignal iOS SDK allow apps to use location targeting for push notifications (geofence notifications). Apple appears to now be scanning apps for any code that uses location services, even if the app doesn’t actually use it. 

Which is....senseless and annoying. 

In the short term I would recommend putting an `NSLocationAlwaysUsageDescription` string in your `Info.plist` even if your app doesn’t actually use it. If your app calls `setLocationShared(false)` our SDK will not prompt the user for location permission. 

It’s annoying, but that’s Apple for you. 

In the long term, splitting out the location functionality into a separate OneSignal/Location Cocoapod library should be a more permanent fix.

**Comment by JEKos** [comment] 2019-03-29 10:53
@Nightsd01 After doing what you said (Adding NSLocationAlwaysUsageDescription and setLocationShared(false)) I'm getting the follow email...

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "P-MORE". Please correct the following issues, then upload again.
> 
> Best regards,
> 
> The App Store Team

Probably their system is broken at this time.

**Comment by tbrand-aa** [comment] 2019-03-29 11:26
I've done the same as @JEKos , also still got this app store connect issue report.
Really hope it's a temporary App Store issue.

**Comment by blocksninja** [comment] 2019-03-29 11:27
> @Nightsd01 After doing what you said (Adding NSLocationAlwaysUsageDescription and setLocationShared(false)) I'm getting the follow email...
> 
> > Dear Developer,
> > We identified one or more issues with a recent delivery for your app, "MY APP NAME". Please correct the following issues, then upload again.
> > Best regards,
> > The App Store Team
> 
> Probably their system is broken at this time.

I've done the same, also same error. Hope it's a temporary App Store issue.

**Comment by gnoph** [comment] 2019-03-29 13:58
We submitted the build without CoreLocation framework in xcode project and still got the same warning from Apple. The framework wasn't actually used before I removed it, it's just in the project but not linked to any of the targets. I think removing it didn't make a difference to the app binary.

> 
> 
> @gnoph Good to hear that removing the library still lets you build. It might be that Apple detects it's use at runtime when evaluating the app so removing Core Location means that OneSignal won't even try to check permission. The might be doing some static analysis though, it's hard to say.
> 
> Keep us updated on what your latest submission results in.

**Comment by JEKos** [comment] 2019-03-29 14:44
and here is the solution, and yes it's that stupid thing.. https://stackoverflow.com/a/55412107/5375263

I just tested it, by changing it from `Advertisement` to `Need permission for better user experience` and the build have finished successfully on Apple Connect

**Comment by bolino** [comment] 2019-04-03 17:51
Can anyone confirme that calling `setLocationShared(false)` without adding the strings to `Info.plist` works? Or are we supposed to do both things?

**Comment by Nightsd01** [comment] 2019-04-03 18:42
@bolino add the strings to your `Info.plist`. It’s a silly situation thanks to Apple but unfortunately that’s the current solution. Fortunately none of this will be visible to your users.

**Comment by vitovalov** [comment] 2019-06-26 18:52
Same!

Please split the pod ASAP. 

Had to fill this question to find out the answer that pointed me here. 
https://stackoverflow.com/q/56777940/860311

**Comment by stsier** [comment] 2019-08-04 23:51
Just use

NSLocationAlwaysAndWhenInUseUsageDescription

instead of NSLocationAlwaysUsageDescription + NSLocationWhenInUseUsageDescription

Apple is so stupidly secrete about their tweeks..

**Comment by skibitsky** [comment] 2020-04-20 15:19
Same in v2.13.

>ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

>ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by DanielZ15** [comment] 2020-05-05 19:40
> Thanks for the helpful info. It looks like Apple is simply scanning the bitcode for any usage of location services. Our SDK accesses location services indirectly to avoid a crash if an app doesn’t use location services, so they must be scanning strings too....
> 
> It’s a bit ridiculous considering how many dependencies/frameworks use location services but only under certain conditions that may not be applicable to some apps.
> 
> I’ll keep this issue open until we’ve found a solution.
> 
> As a temporary workaround, if you don’t use location-based push notifications, you can call `OneSignal.setLocationShared(false)`. That will turn off location access from our SDK. If you add the location permissions to your info.plist, Apple will stop sending you those warnings, but as long as your app never requests location permission, the plist strings will go unused.

hi @Nightsd01 . I realize your replies here are couple years back now. But I'm experiencing this now as a warning (testflight only, I don't have a production build yet). And I was wondering if you know if we do use this workaround (thank you for that btw), do you know by any chance if "Location" will appear under "Information" on the app page in the app store? That's my concern as it might deter downloads since people may think we use the location when we actually don't. Thanks!

**Comment by JetForMe** [comment] 2020-06-04 09:24
I just integrated OneSignal into my iOS app and got this warning tonight, after having submitted earlier builds that didn't.

**Comment by SwiftiSwift** [comment] 2020-06-21 18:31
Still getting this E-Mail:

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).After you’ve corrected the issues, you can upload a new binary to App Store Connect.Best regards,The App Store Team | ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).After you’ve corrected the issues, you can upload a new binary to App Store Connect.Best regards,The App Store Team
> -- | --
> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).After you’ve corrected the issues, you can upload a new binary to App Store Connect.Best regards,The App Store Team

**Comment by JetForMe** [comment] 2020-06-21 21:59
I sometimes get the warning, sometimes don't.

**Comment by MihaMarkic** [comment] 2020-07-23 17:09
Silly question, but what would somebody put into NSLocationAlwaysAndWhenInUseUsageDescription (or NSLocation***)? I mean, afterall the app isn't using it...

**Comment by SwiftiSwift** [comment] 2020-08-08 10:39
@MihaMarkic 'We need to access your Location to send you proper notifications' for example

**Comment by Pedro-vzla** [comment] 2022-11-24 18:39
Nov 24, 2022. still happening. The first time I had my app uploaded to testflight then approved in app store I did not get this email but now that I change literally one line of code ( updating a URL in the code ) I get the email. I set the NSLocationAlwaysAndWhenInUseUsageDescription string and hope this is going to help me in the approval
![onesignal_location_issue](https://user-images.githubusercontent.com/58534795/203849028-016a5061-d00b-4418-914f-c70c2e16bfda.png)

**Comment by donmb1** [comment] 2022-11-30 15:13
I also receive this when uploading my build to Appstore Connect

**Comment by mariomka** [comment] 2022-12-05 08:57
I also receive this after updating from 3.11.2 to 3.11.4.
Maybe these changes have something to do with it? https://github.com/OneSignal/OneSignal-iOS-SDK/commit/0102f9a47de5a7742552c70c526eb8eddad5235f

**Comment by mrzystem** [comment] 2023-04-02 17:30
I am receiving this message now too. My app does not use location services, no background mode, and setLocationShared is false.

framework version 3.12.4

**Comment by mrzystem** [comment] 2023-04-02 19:09
I'm now also getting this warning: ITMS-90683: Missing purpose string in Info.plist

_The Info.plist file for the “x.app” bundle should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data._

My app is not using location services. Background services are also not enabled and `OneSignal.setLocationShared(false)` is called before init.

Framework version 3.12.4

**Comment by donmb1** [comment] 2023-04-18 13:15
This is still an issue

**Comment by donmb1** [comment] 2023-04-20 09:57
@nan-li I can confirm that my app still got approved despite the warning message
however I would not give much on that because the Apple approval process is pretty random

**Comment by Aulig** [comment] 2023-07-04 08:11
Happening to me too - can you reopen the issue please @Nightsd01

**Comment by bitjunk** [comment] 2023-08-02 21:27
Same started happening again! Really hope we get a new SDK without the location thing given that it's been going on for years!!

**Comment by khushalkhan83** [comment] 2023-09-05 15:00
reopen it, its still an issue

**Comment by RMatushkin** [comment] 2023-09-10 21:37
I was able to completely disable the module 'OneSignalLocation', here's a quick guide on 5.0.0 version:

1. You have to fork this repository to make your own version of OneSignal dependency.
2. Edit "ios/onesignal_flutter.podspec" file to have something like that:
```
Pod::Spec.new do |s|
  s.name             = 'onesignal_flutter'
  s.version          = '5.0.0'
  s.summary          = 'The OneSignal Flutter SDK'
  s.description      = 'Allows you to easily add OneSignal to your flutter projects, to make sending and handling push notifications easy'
  s.homepage         = 'https://www.onesignal.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Brad Hesse' => 'brad@onesignal.com', 'Josh Kasten' => 'josh@onesignal.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  # s.dependency 'OneSignalXCFramework', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignal', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalCore', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalExtension', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalInAppMessages', '5.0.1'
  # s.dependency 'OneSignalXCFramework/OneSignalLocation', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalNotifications', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalOSCore', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalOutcomes', '5.0.1'
  s.dependency 'OneSignalXCFramework/OneSignalUser', '5.0.1'
  s.ios.deployment_target = '11.0'
  s.static_framework = true
end
```
Please note that I commented "OneSignalXCFramework" to exclude the whole dependency and then I define all necessary submodules, and you can comment "OneSignalLocation" or don't add it indeed.

3. Use this version of the dependency in your project, add such lines in "pubspec.yaml":
```
onesignal_flutter:
  path: '<PATH>'
```
4. Update "Podfile":
```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework/OneSignal', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalCore', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalExtension', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalInAppMessages', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalNotifications', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalOSCore', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalOutcomes', '>= 5.0.0', '< 6.0'
  pod 'OneSignalXCFramework/OneSignalUser', '>= 5.0.0', '< 6.0'
end
```
Please note that I didn't add "OneSignalXCFramework" and defined all submodules instead.

**Comment by bitjunk** [comment] 2023-09-10 22:10
@RMatushkin Thanks for sharing! I wouldn't mind forking and doing all that work if it was free software but it's not. I do pay for it and it's cumbersome to do that patch work for all the future version upgrades.

**Comment by RMatushkin** [comment] 2023-09-11 12:26
> @RMatushkin Thanks for sharing! I wouldn't mind forking and doing all that work if it was free software but it's not. I do pay for it and it's cumbersome to do that patch work for all the future version upgrades.

You are correct; developers should offer the ability to exclude modules without requiring manual manipulation. However, since this issue has remained unresolved for many years, it might be quicker to take matters into your own hands. I can't afford to wait indefinitely and delay the release of new apps.

**Comment by ashleydee1999** [comment] 2023-10-03 09:22
I can confirm that this is still an ongoing issue, I'll try the workaround

**Comment by khushalkhan83** [comment] 2023-10-03 13:40
One signal sdk caused cyclic dependency in xcode build i have to remove one signal from ios

**Comment by KChanduu** [comment] 2025-06-01 14:32
It is still same, 6 months earlier, i did not face this issue but today i was implementing in new app & now this error.

**Comment by nan-li** [comment] 2025-06-02 18:10
Hi @KChanduu thanks for your question. You should include the OneSignal SDK dependencoes separately and omit the OneSignalLocation dependency. Please see the section titled "**1. Add SDK**" in our[ iOS setup documentation](https://documentation.onesignal.com/docs/ios-sdk-setup#1-add-sdk) for how to include the individual dependencies via SPM and Cocoapods.
