### ISSUE TITLE
setNotificationWillShowInForegroundHandler -> completion(nil) doesn't work 

### ISSUE THREAD

**Issue by billypap1** [OneSignal/OneSignal-iOS-SDK#989] opened 2021-09-01 22:24 UTC
**Description:**

We have integrated successfully  OneSignal to our iOS App and we can receive notifications even if our app is terminated/background. Our main issue is that we can't prevent notification from showing when app is in foreground. 
We use the code below (this exist in your docs) but it doesn't work and the notification is showing as always when app is in foreground: 

```
let notificationWillShowInForegroundBlock: OSNotificationWillShowInForegroundBlock = { notification, completion in
          print("Received Notification: ", notification.notificationId ?? "no id")
          print("launchURL: ", notification.launchURL ?? "no launch url")
          print("content_available = \(notification.contentAvailable)")

            completion(nil)
          
        }

        OneSignal.setNotificationWillShowInForegroundHandler(notificationWillShowInForegroundBlock)
```

We want always to prevent notification from showing when app is in foreground.

**Environment**
1. What version of the iOS SDK are you using?
OneSignalXCFramework (3.7.0) version of SDK
2. How did you add the SDK to your project (eg. cocoapods)
Cocoapods

**Steps to Reproduce Issue:**

  1. Install iOS SDK version 3.7.0 with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Attempt to receive a push notification
 4. set OneSignal.setNotificationWillShowInForegroundHandler(notificationWillShowInForegroundBlock)

**Comment by emawby** [comment] 2021-09-02 17:07
@billypap1 Odd this is working for me using your exact code. Are you sure that the `notificationWillShowInForegroundBlock` is actually being run? Do you have any other dependencies that might intercept push related events?

**Comment by billypap1** [comment] 2021-09-02 19:10
@emawby No, i don't have any other dependencies that might intercept push related events. The notificationWillShowInForegroundBlock runs successfully and when I set it -> completion(nil)  the notification is displayed as always. Is this a bug? This is a very critical issue for our app.

**Comment by emawby** [comment] 2021-09-02 22:28
@billypap1 Are you able to provide an example app with the issue? I am not able to reproduce this. What iOS version are you testing on?

**Comment by billypap1** [comment] 2021-09-02 22:42
@emawby I just use the code that you provide in your docs, nothing else. I'm using  iOS 14.6.

**Comment by emawby** [comment] 2021-09-02 23:42
@billypap1 Unfortunately it is difficult to diagnose what could be going wrong in your app since the code you posted is working as expected for my test applications. It would be helpful to debug an application that is experiencing this issue if at all possible.

Just to confirm, are you sending the notification via the OneSignal dashboard?

**Comment by emawby** [comment] 2022-01-13 19:16
Closing for now. If this is still an issue please reopen. Providing an example app that has this issue would also be helpful!

**Closed by emawby** 2022-01-13 19:16 UTC
Labels: Help Wanted, Non-Reproducible

**Comment by mdotadil** [comment] 2022-06-03 14:41
I'm experiencing the same issue. @billypap1 Please share some insight on how to resolve this.

**Comment by vinczebalazs** [comment] 2022-11-13 17:45
setNotificationWillShowInForegroundHandler is never called when testing on the simulator by dragging a .apns file. Could that be the issue?
