### ISSUE TITLE
IDFA collection is resulting in app rejection

### ISSUE THREAD

**Issue by wassimseif** [OneSignal/OneSignal-iOS-SDK#778] opened 2020-10-22 07:43 UTC
**Description:**

App is being rejected now because of IDFA collection. I have made sure that `AdsSupport.framework` is not linked anywhere in my App.
I was wondering if there's a way to stop collection.I understood that the IDFA is used to avoid duplicate rows across installs on the same device but I think this is an okay downside.

**Environment**

1. What version of the iOS SDK are you using? OneSignal (2.15.3)
1. How did you add the SDK to your project : Cocoapods

**Comment by rgomezp** [comment] 2020-10-22 18:47
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1029

**Comment by ilyakar** [comment] 2020-10-24 21:51
Yup. This is the best I got from Apple's responses:

![image](https://user-images.githubusercontent.com/1760709/97094279-78cd2280-164b-11eb-983e-ab063188c87d.png)

**Comment by emawby** [comment] 2020-10-28 23:40
The fix for this is merged and will be available in the next released version

**Comment by wassimseif** [comment] 2020-10-29 08:59
@emawby Thank you for the fast solution.

is there anyway to directly install the SDK with this commit ?

**Comment by emawby** [comment] 2020-10-30 18:06
> @emawby Thank you for the fast solution.
> 
> is there anyway to directly install the SDK with this commit ?
@wassimseif 
Yes you could link against the master branch instead of a release version. We will not be releasing any SDK updates until later next week.

**Comment by wassimseif** [comment] 2020-10-31 09:13
@emawby Yes that's what i did eventually. Thank you !

**Closed** 2020-11-11 21:07 UTC
Labels: Bug: Medium Priority

**Comment by ilyakar** [comment] 2020-11-16 12:56
Mmm. So I tried the latest "removing IDFA usage from OneSignal" commit, pushed to Apple. Rejection still happening.

Did: `grep -lr "advertisingIdentifier" * | grep -v .svn | grep -v .md` to check what's using the advertisingIdentifier and OneSignal is still using it in plenty of places:
```
ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/A/OneSignal
ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/Current/OneSignal
ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal
ios/build/Einee/Build/Products/Debug-iphonesimulator/Einee.app/Einee
node_modules/react-native-onesignal/ios/libOneSignal.a
```

I believe the IDFA fix needs to be looked into again.

**Comment by ilyakar** [comment] 2020-11-16 14:46
@emawby ah, it seems the framework needs to be rebuilt. I can't quite figure out how to do this, are you able to rebuild the framework using the new IDFA changes and push the commit?

**Comment by wassimseif** [comment] 2020-11-16 15:07
@ilyakar Yes that's what i did to make it work. If you want I can send you the built .framework

**Comment by ilyakar** [comment] 2020-11-16 15:21
@wassimseif yes please! ilya@round-rabbit.com

Did you need to change anything in react-native-onesignal to get it past the review?
As I see `node_modules/react-native-onesignal/ios/libOneSignal.a` is referencing to advertisingIdentifier also.
