### ISSUE TITLE
Crash on iOS 11 with class_getSuperclass - SDK 2.5.4 through 2.5.6

### ISSUE THREAD

**Issue by aaronbrethorst** [OneSignal/OneSignal-iOS-SDK#278] opened 2017-09-19 07:15 UTC
This happens inconsistently, unfortunately. I imagine that turning this from a `do-while` to a straight-up `while` loop would fix the issue. You can check out the project where this is happening at https://github.com/OneBusAway/onebusaway-iphone/

<img width="765" alt="screen shot 2017-09-19 at 12 14 03 am" src="https://user-images.githubusercontent.com/2254/30579923-8ee05bda-9ccf-11e7-8c37-5bbde17fc49b.png">

**Comment by anushkmittal** [comment] 2017-09-19 22:14
I think it's the same issue as #274. @jkasten2 Can you reproduce the issue with this repo?

**Comment by aaronbrethorst** [comment] 2017-09-19 22:27
Yeah, this looks like the same issue to me. I'm happy to help out in any way I can.

**Comment by jkasten2** [comment] 2017-09-21 00:05
@aaronbrethorst Tried building and running the project you linked to above. Launched the app a number of times on iOS 11 on both a simulator and a real device and wasn't able to reproduce the issue. However I agree with your suggestion on preventing any possible nil errors.

The fix will be available in the next release.

**Comment by aaronbrethorst** [comment] 2017-09-21 05:44
Cool, thank you! Do you have an estimated date for release?

**Comment by hixfield** [comment] 2017-09-24 06:47
I have build against master but still see the issue popping up (same location as screenshot above). Maybe something went wrong with your push/merging to master?

**Comment by jkasten2** [comment] 2017-09-25 21:10
@hixfield I have verified the change is on master correctly.
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignalSelectorHelpers.m#L103

Can do clean build to ensure you have the change in your project? If you are still seeing a crash can you verify the stack trace isn't different in anyway?

**Comment by gerbiljames** [comment] 2017-09-26 14:04
If you're using CocoaPods you can't just point it at the master branch in this repo because it will just pull the prebuilt framework down, which doesnt have the fix yet. I worked around this by forking the repo, compiling the framework and pushing it to the fork, then pointing CocoaPods at the fork. I assume it would be the same with other dependency managers too.

**Comment by hixfield** [comment] 2017-09-26 15:46
I am using cartage

**Comment by hixfield** [comment] 2017-09-28 17:34
This is the contents of my cart file:

github "OneSignal/OneSignal-iOS-SDK" "master"

I verified in the carthage/checkouts folder and can confirm that the source includes the fix.
Maybe something else went wrong, I will do a rebuild (including carthage) and keep an eye on it to see if it happens again.

**Comment by gerbiljames** [comment] 2017-09-29 13:28
The crash is still happening for me even with the fix applied. If you want to test with the applied fix change your carthage line to:

`github "gerbiljames/OneSignal-iOS-SDK" "master"`

**Comment by DaveWoodCom** [comment] 2017-09-29 19:52
FYI, I was also seeing this crash. I've switched to this fork: https://github.com/franklyinc/OneSignal-iOS-SDK and haven't seen the crash since.

**Comment by alexandre-g** [comment] 2017-10-03 08:11
@DaveWoodCom For me 19/46 UITests failed due to this crash before switching to franklyinc's fork, and 2/46 after. So much better but still crashing.

**Comment by jkasten2** [comment] 2017-10-03 19:01
@alexandre-g Could you share the 2 stack trace of the 2 crashes you are still getting?

**Comment by alexandre-g** [comment] 2017-10-04 02:09
@jkasten2 I don't see a way to get them from Integration logs but have a colleague who is writing new tests and asked him to take a screenshot when he encounters

**Comment by alexandre-g** [comment] 2017-10-04 08:11
@jkasten2 Actually there is a way to get the crash logs, strange that I didn't see it the first time I looked.

http://goloskok.com/u/snippet-mwPOMZUK3q.txt

**Comment by jkasten2** [comment] 2017-10-06 23:09
Reopening, report of this issue still happening on issue #240

**Comment by Hendies567** [comment] 2017-10-12 13:18
Still getting this crash on 2.5.6, sometimes it can be as bad as every other launch via Xcode's simulator

**Comment by alexandre-g** [comment] 2017-10-12 14:40
@jkasten2 I've tried reproducing this on a new project with OneSignal initted same way, but couldn't get it to crash. So then I approached it from the other direction - I've started stripping away code and files from the original project to see at what stage it would stop crashing, but could not find the exact place. It seemed like the more files I remove, the less often the crash occurs

**Comment by vitalii-tym** [comment] 2017-10-12 16:12
Have anyone experienced this crash on real iOS device? I wonder whether this is simulator-only or not and whether it will affect real users.

**Comment by DaveWoodCom** [comment] 2017-10-12 16:40
I'm pretty sure I was getting this crash on real devices, but can't say 100% since the crash logs weren't very useful. But the crashes did go away when I switched to the https://github.com/franklyinc/OneSignal-iOS-SDK fork.

**Comment by gharary** [comment] 2017-10-13 16:13
I have the same issue with the latest release happening on simulator.

**Comment by jstheoriginal** [comment] 2017-10-15 19:18
I have never had this happen on a real device, according to Fabric...however I'm not sure if Fabric would even report it properly if it did since it's so early at launch.

**Comment by revolter** [comment] 2017-10-15 20:21
Me neither, but it looks like it depends on other custom code too.

**Comment by YBthebest** [comment] 2017-10-15 21:10
Still having this issue with the latest release of OneSignal. Can't confirm or deny if I've had it on a real device though.

**Comment by HackShitUp** [comment] 2017-10-18 21:59
I also still continue to have this error, but it only occurs on the simulator.

**Comment by jkasten2** [comment] 2017-10-18 22:01
Is the stack trace any different on version 2.5.6 than the original post? Is it still crashing on `class_getSuperclass`?

**Comment by laurent-humbert** [comment] 2017-10-19 08:53
Still crashing at the same place. Version 2.5.6.
![screen shot 2017-10-19 at 10 51 46](https://user-images.githubusercontent.com/19427074/31762509-ba7ccdc4-b4bb-11e7-954b-7a2471184b86.png)

**Comment by Hendies567** [comment] 2017-10-20 15:37
For me, the bug occurs exactly as shown above by laurent-humbert. I believe it only happens when running via Xcode's simulator - not on a physical device. Here's a screenshot of the crash:
<img width="732" alt="screen shot 2017-10-20 at 16 32 49" src="https://user-images.githubusercontent.com/26363840/31829265-a93491e2-b5b4-11e7-8756-52a89e4b21a1.png">

**Comment by revolter** [comment] 2017-10-23 12:59
It crashes every time on device if `Malloc Scribble` is enabled.

**Comment by Hendies567** [comment] 2017-10-26 21:53
Do you have an ETA or any updates on a fix for this?

**Comment by jkasten2** [comment] 2017-10-31 02:52
@revolter Thanks, however still was not able to reproduce the issue on a simulator or device.

### OneSignal SDK Debugging
I have created a debug branch that will output all class names before `class_getSuperclass` is called on them. This is the [getSuperclass_debugging](https://github.com/OneSignal/OneSignal-iOS-SDK/tree/getSuperclass_debugging) branch. Copy  and replace the `iOS_SDK/OneSignalSDK/Framework/OneSignal.framework` from this branch into your project replacing the current OneSignal SDK.
The output from this could be rather long, only the first 20 or so lines and the last 20 or so lines is needed to debug the issue.

### Zombie Objects
With or without the debug version above enabling "Zombie Objects" may provide some extra entries to the xcode log while the app is running that will be helpful.
![image](https://user-images.githubusercontent.com/645861/32205275-9a69bdbe-bdab-11e7-9602-57b74b61d474.png)

**Comment by revolter** [comment] 2017-10-31 09:01
With this new framework, it doesn't crash. I previously had version 2.5.4 installed.

**Comment by depoon** [comment] 2017-11-02 15:48
I've created this pull request https://github.com/OneSignal/OneSignal-iOS-SDK/pull/297 to provide the option of disabling OneSignal.load() without altering much of the codes.

Simply pass `DISABLE_ONESIGNAL` as arguments to ProcessInfo. This is useful for selectively turning off OneSignal.load() for simulator builds or XCUITest (which is failing for me)

<img src='https://i.imgur.com/NwAjqm0.png' />

This is my fork branch
https://github.com/depoon/OneSignal-iOS-SDK/tree/DisableOneSignalUsingInfoProcessToFixCrash

**Comment by gbtagliari** [comment] 2017-11-02 16:46
I made a PR to fix simular crash on simulator. (https://github.com/OneSignal/OneSignal-iOS-SDK/pull/298)

**Comment by jkasten2** [comment] 2017-11-03 06:25
I am now able to reproduce this crash. I have branch with a fix available below.
https://github.com/OneSignal/OneSignal-iOS-SDK/tree/ios11_startup_crash_fix

After some additional testing it will be released in the next update.

**Closed** 2017-11-08 00:52 UTC
Labels: bug

**Comment by jkasten2** [comment] 2017-11-08 20:02
The fix is now included in the [2.5.7 SDK Release](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.5.7).

**Comment by joshuapoq** [comment] 2021-07-07 12:04
I don't know if this is still an issue as it's a few years old and closed but I found with similar Swift code that I doubt this fix will have worked.

For me the app will crash on launch during a random one of our hundreds of tests - the expected count from the first call is different to the actual count from the second call.

To fix this I throw away the memory and recursively call the function if the two counts do not match; it's not perfect so you could add a loop limit but I've found the second run the counts are the same. I assume some class definition is being added between the two calls.

**Comment by punitbansal-kt** [comment] 2022-07-07 03:10
We are still experiencing this crash on iOS 15.5. as well. The onesignal version that we are using is 3.10.1. We are not able to reproduce it in dev environment but in our crashlytics we can see it occurring quite often. 

Crash logs
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x8edc class_getSuperclass + 4
1  OneSignal                      0x2bf28 __hidden#2176_ + 128 (__hidden#2177_:128)
2  OneSignal                      0x380b4 __hidden#2755_ + 200 (__hidden#2800_:200)
3  OneSignal                      0x38048 __hidden#2754_ + 192 (__hidden#2800_:192)
