### ISSUE TITLE
no architectures in the binary. lipo failed to detect any architectures in the bundle executable 

### ISSUE THREAD

**Issue by arihantop** [OneSignal/OneSignal-iOS-SDK#1232] opened 2023-02-27 06:11 UTC
### How can we help?

I am getting this error while I am uploading the ios app on app store after successfull archiving.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/106806839/221488032-b03ec08c-ce09-43b2-9ecc-d0832c12d24b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment] 2023-03-07 16:20
Hi @arihantop,
What version of the OneSignal-iOS-SDK are you using?

**Comment by emawby** [comment] 2023-03-16 17:02
Closing for now feel free to reopen if this is still an issue.

**Closed by emawby** 2023-03-16 17:02 UTC
Labels: Need More Information

**Comment by ShvetsovZE** [comment] 2024-05-14 06:37
I have exactly the same issue. @arihantop did you find any solution? @nan-li , @emawby using  framework 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'.  Do have any ideas what can cause it?

**Comment by chibombo** [comment] 2024-06-17 19:43
Same issue here

**Comment by shplishka** [comment] 2024-09-27 08:10
anyone can help with this?

**Comment by grobarko** [comment] 2024-10-03 09:30
Same issue here

**Comment by chibombo** [comment] 2024-10-03 14:03
In my case, this issue was caused by a wrong bundle id configuration. 
- Set the correct bundle id for the extension
- Same for the Target
- Same for the entitlements file

**Comment by guneyural** [comment] 2024-10-04 23:28
I faced the same issue and here's how I solved it:

- Open xcode, select your project and from targets select ``OneSignalNotificationServiceExtension``
- Open ``Build Phases`` tab
- Expand ``Compile Sources`` section
- Make sure ``NotificationService.swift``file is listed there, otherwise add that file from plus icon.

That's how I solved this issue.

``NotificationService.swift`` file should be located in ``OneSignalNotificationServiceExtension/NotificationService.swift`` path.
