### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException Attempt to add non-NSObserver object <OSEmailSubscriptionChangedInternalObserver: 0x283cbe470> as an observer of <GPBFieldDescriptor: 0x281d8e080>

### ISSUE THREAD

**Issue by mhaseeb1996** [OneSignal/OneSignal-iOS-SDK#710] opened 2020-07-14 14:25 UTC
Description:
Currently i am using one signal sdk version 2.14.2 in my ios application for push notification 
Everything is working fine but today i saw a crash, can anyone suggest how i can solve this issue or just update the sdk to 2.14.3?

<img width="1114" alt="Screen Shot 2020-07-14 at 7 29 20 PM" src="https://user-images.githubusercontent.com/64838588/87437996-71d45400-c608-11ea-868f-010cd3e1202b.png">

ios version is 13.3.1

Crash occur on live app  
code that i am using to in appdelegate didfinishLaunching with options 
<img width="808" alt="Screen Shot 2020-07-14 at 7 35 09 PM" src="https://user-images.githubusercontent.com/64838588/87438664-46059e00-c609-11ea-845a-b3c8a64b1eb1.png">

**Comment by rgomezp** [comment] 2020-07-23 18:37
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/523

**Closed by rgomezp** 2020-07-23 18:37 UTC
Labels: Help Wanted

**Comment by rgomezp** [comment] 2020-07-23 18:38
I reopened the other issue where you can track this problem. Also please update to the latest SDK
