### ISSUE TITLE
[Bug]: Upload version to store

### ISSUE THREAD

**Issue by osama450** [OneSignal/OneSignal-iOS-SDK#1437] opened 2024-05-16 23:15 UTC
### What happened?

i get this 2 issues when upload version to store :

Asset validation failed (90206)
Invalid Bundle. The bundle at 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed file 'Frameworks'. (ID: 53a5c750-38f5-4b2b-ab38-ab2a435d49ed)

Asset validation failed (90205)
Invalid Bundle. The bundle at 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed nested bundles. (ID: 0506a1cf-0cb0-4ffb-ba90-0fc8dcdd8362)

### Steps to reproduce?

```Markdown
1 : try to upload version from xcode
```

### What did you expect to happen?

.

### OneSignal iOS SDK version

5.1.6

### iOS version

17, 16, 15, 14, 13, 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment] 2024-05-17 05:40
closing as duplicate of https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/888

**Closed by nan-li** 2024-05-17 05:40 UTC
