### ISSUE TITLE
Unable to add as a dependency

### ISSUE THREAD

**Issue by armandsLa** [OneSignal/OneSignal-iOS-SDK#271] opened 2017-09-08 12:29 UTC
I was unable to add OneSignal as dependency to a development pod. Seems like this requires some addition configurations described [here](https://github.com/CocoaPods/CocoaPods/issues/5368).

**Comment by rgomezp** [comment] 2019-04-03 00:03
Closing issue. Note: request still under consideration

**Closed by rgomezp** 2019-04-03 00:03 UTC
Labels: improvement

**Comment by jkasten2** [comment] 2019-09-30 20:41
@armandsLa Is this is still an issue? Since this was opened a while back there have been a number of changes to both this SDK and Cocoapods.

Our React Native SDK depends on this SDK via Cocoapods noted in this podspec.
https://github.com/geektimecoil/react-native-onesignal/blob/3.4.1/react-native-onesignal.podspec#L24-L25

If you are still able to reproduce a problem can you attach an example project?
