### ISSUE TITLE
Handling VOIP Push and Regular Push Together Issue

### ISSUE THREAD

**Issue by nomimalik1769** [OneSignal/OneSignal-iOS-SDK#415] opened 2018-09-18 15:01 UTC
**Description:**

My Problem is I have added regular push in my app and those are working perfectly fine. Now I need VOIP Push for calling feature but I am unable to do so. I have created VOIP .Cer and uploaded it on OneSignal. I have created **new APP on OneSignal** for VOIP Push Only. I have added new Device API cal in My App to register new Device in that App. 

I have one APP ID which I am using in oneSignal Init Method which is sending me Regular Push and One APP ID from which I am registering new Device. Now My Issue is When I used Player ID of 2nd APP which is created for VOIP Push are not coming but When I use 1st APP which isCreated for Normal Push Notification are coming. I have Added different certificate in Both OneSignal App. Now how will I  handle both APP and send Voip Push When Needed.

**Environment**

1. I am using iOS 11.4 and OneSignal Latest Version.
2. I have Added one Signal SDK using CocoaPods.

**Comment by Nightsd01** [comment] 2018-09-19 17:08
Here is a doc for this situation: https://documentation.onesignal.com/docs/voip-notifications

**Comment by nomimalik1769** [comment] 2018-09-20 09:33
This doc doesn't do any justice. It's incomplete in so many ways.

**Comment by Nightsd01** [comment] 2018-09-20 17:26
@nomimalik1769 because VOIP and normal push notifications use different certs, they’ll need to be assigned to different App ID’s on our end. And because of that you’ll get two user ID’s, one for push and one for VOIP. 

When you want to send a VOIP notification you’ll need to send it to the VOIP player ID. 

I’m not sure I understand your exact issue. You’re saying you’re not receiving the VOIP notifications? What kind of error are you seeing?

**Comment by nomimalik1769** [comment] 2018-09-21 05:51
Yes I know I will have to receive VOIP with different APP ID.
 But is it possible to initialise OneSignal two time in you App with two different APP IDS.?

**Comment by Nightsd01** [comment] 2018-09-21 16:51
@nomimalik1769 No it is not. Basically - as the article above outlines, for the VOIP push token you get, you have to make a REST API call to our server to get a OneSignal user ID.

Unfortunately our SDK is not currently very optimized for VOIP notifications. In the mean time, that workaround should work.

Closing because this is not a bug

**Closed by Nightsd01** 2018-09-21 16:51 UTC

**Comment by tupperkion** [comment] 2019-05-15 16:21
Quick question: Can you use the same app ID for FCM and VoIP, making it possible to use the same app ID for iOS (VoIP) and Android (FCM) apps? Also does VoIP work well with user data tags for segmentation?

**Comment by KishanVyas** [comment] 2019-10-02 05:49
@nomimalik1769 , @Nightsd01  ,  hi, did you find any solution of this. I am also suffering the same issue. I followed the same steps of OneSignal documents. But when I am sending notification using CURL command by passing separate VoIP app's player id, I am not getting VoIP push notification. But when I am using "Pusher" app to send VoIP notification, I am receiving VoIP notification.

**Comment by chellongCoder** [comment] 2020-12-30 08:11
> @nomimalik1769 , @Nightsd01 , hi, did you find any solution of this. I am also suffering the same issue. I followed the same steps of OneSignal documents. But when I am sending notification using CURL command by passing separate VoIP app's player id, I am not getting VoIP push notification. But when I am using "Pusher" app to send VoIP notification, I am receiving VoIP notification.

same to me

**Comment by yehyaumar** [comment] 2021-11-25 06:34
Please reopen this issue. I'm facing exactly the same. I have followed documentation, uploaded VoIP certificate and registered device with VoIP token and the device shows in the onesignal app as well. But I'm neither receiving VoIP notification (via API / onesignal-node sdk) nor a normal push notification (via onesignal dashboard).

**Comment by yehyaumar** [comment] 2021-11-26 04:12
After tirelessly searching for the solution, I finally stumbled upon this article which is actually working. One Signal documentation in this regard is very misleading and incomplete.
For anyone who is still looking, [check here](https://medium.com/monyneathmol/voip-notification-with-onesignal-complete-setup-in-ios-c376a829392e)
