### ISSUE TITLE
get player BEFORE user subscribes

### ISSUE THREAD

**Issue by ajRiverav** [OneSignal/OneSignal-iOS-SDK#483] opened 2019-01-21 18:41 UTC
**Description:**

I have not seen this question asked before. How can one get the player id _before_ the user subscribes? I remember in Kotlin (Android) this is posible, but I have not found a way to do it on iOS.

**Comment by Nightsd01** [comment] 2019-01-21 19:13
@ajRiverav iOS will register either (A) when the user accepts push permission or (B) after 30 seconds, whichever comes sooner. This is done to prevent unnecessary API traffic since there’s no point in making an API request if they’ll just end up registering in seconds anyways

**Comment by ajRiverav** [comment] 2019-01-21 21:19
in reagard to B,
What triggers the 30 second timer? 
Is an event generated? That is, is onOSSubscriptionChanged() invoked?

**Comment by Nightsd01** [comment] 2019-01-21 21:32
It is controlled by `shouldRegisterNow()` in `OneSignal.m`. But I would not recommend changing it. Why do you need it immediately...? There’s probably a better way of doing whatever it is you’re trying to accomplish.

**Comment by ajRiverav** [comment] 2019-01-22 15:15
@Nightsd01 

In the current design, we use the player id _before_ we ask for permissions. This is to avoid bothering the user with permissions before it makes sense to ask for them (UX decision). 

Now, I was reading the OneSignal.m code and saw a few things:

Line https://github.com/OneSignal/OneSignal-iOS-SDK/blob/aa59b92fb0b9c0a5343bdd5346282212de80976c/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1458
states 
> Make sure we only call create or on_session once per open of the app.

However, I did not see that happening (it's called twice). Line shows: 
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/aa59b92fb0b9c0a5343bdd5346282212de80976c/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1405

So, if one is using the app for the first time, `lastTimeCalled` is set to the time the app was opened, or so, AND THEN it returns true, triggering a call to `onOSSubscriptionChanged()`. That is why I observed that the first time the app is used, inside `onOSSubscriptionChanged()` `stateChanges.to.userId` is nil. 

30 seconds later, stateChanges.to.userId is not nil.

I have been trying to understand the reasoning behind the 30-second timer (as opposed to, say, 1 second). Any thoughts on that? I know you said this is to prevent unnecessary API traffic, but if the user takes more than 30 seconds to give permissions, this will be called twice anyway.

**Comment by Nightsd01** [comment] 2019-01-22 15:19
@ajRiverav the user in our experience _almost never_ takes 30+ seconds to answer the prompt. It’s incredibly rare. This is why it’s extremely uncommon for us to see multiple `on_session` calls. 

And as I said before, the reason it’s 30 seconds and not 1 second is because if we called it after 1 second almost no users will have answered the prompt by that time. 

You still haven’t actually explained _why_ you need the player ID before asking permission? What is the actual reason?

Closing issue because this is intended behavior of the SDK.

**Closed by Nightsd01** 2019-01-22 15:19 UTC
