### ISSUE TITLE
Version 3.0.0 - Crash Report "onNotificationReceived: + 292" 

### ISSUE THREAD

**Issue by idefen1** [OneSignal/OneSignal-iOS-SDK#811] opened 2020-11-22 20:15 UTC
**Description:**
Released Version 3.0.0 to production apps. Getting 2 main crash reports from Apple (not able to replicate on my physical devices). The first was reported in ticket #806, this is the 2nd "onNotificationReceived: + 292 (see below trace).

I have received these same Crash Reports for both Version 2 and Version 3 of BETA 3.0.0
Edit 12/15 - Now receiving same errors in the Official 3.0.0 release

Environment
Crash Report shows crash occurring on iOS 13.6, 13.7, 14, 14.1, 14.2

Steps to Reproduce Issue:

1. Install iOS SDK 3.0.0 (Official Release, Beta 2, Beta 3) with Cocoapods into a project
1. Followed the 'upgrade' instructions
1. Tested receiving notifications with no issue on my physical device (across all cases: app open, app in background, app closed) - no issues
1. Released new app version into Production
1. Getting new Crash Reports from Apple (Organizer/Crash Reports). Partial crash report below. Error line "onNotificationReceived: + 292".

Any help would be greatly appreciated. Thank you.

**Anything else:**

Thread 3 name:
Thread 3 Crashed:
0   libobjc.A.dylib               	0x0000000199b0adf0 objc_release + 16 (objc-object.h:260)
**1   ...tificationServiceExtensionB	0x0000000104c0a368 +[OneSignalNotificationServiceExtensionHandler onNotificationReceived:] + 292 (OneSignalNotificationServiceExtensionHandler.m:104)**
2   ...tificationServiceExtensionB	0x0000000104c09f68 +[OneSignalNotificationServiceExtensionHandler didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 368 (OneSignalNotificationServiceExtensionHandler.m:60)
3   ...tificationServiceExtensionB	0x0000000104be2004 0x104a9c000 + 1335300
4   ...tificationServiceExtensionB	0x0000000104aa3f5c -[NotificationService didReceiveNotificationRequest:withContentHandler:] + 288 (NotificationService.m:20)
5   UserNotifications             	0x0000000194ad324c -[_UNNotificationServiceExtensionRemoteContext didReceiveNotificationRequest:withCompletionHandler:] + 428 (_UNNotificationServiceExtensionRemoteContext.m:53)
6   Foundation                    	0x00000001875ddd60 **NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S2**

* 12 (NSXPCConnection.m:272)
7   Foundation                    	0x000000018741ba28 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 1736 (NSXPCConnection.m:787)
8   Foundation                    	0x00000001875dde78 message_handler + 224 (NSXPCConnection.m:866)
9   libxpc.dylib                  	0x00000001cbfdf454 _xpc_connection_call_event_handler + 68 (connection.c:0)
10  libxpc.dylib                  	0x00000001cbfdf7d0 _xpc_connection_mach_event + 880 (connection.c:1218)
11  libdispatch.dylib             	0x0000000185e8a340 _dispatch_client_callout4 + 16 (object.m:599)
12  libdispatch.dylib             	0x0000000185e5e600 _dispatch_mach_msg_invoke$VARIANT$armv81 + 376 (mach.c:2429)
13  libdispatch.dylib             	0x0000000185e663c8 _dispatch_lane_serial_drain$VARIANT$armv81 + 260 (inline_internal.h:2589)
14  libdispatch.dylib             	0x0000000185e5f1c8 _dispatch_mach_invoke$VARIANT$armv81 + 464 (mach.c:2751)
15  libdispatch.dylib             	0x0000000185e663c8 _dispatch_lane_serial_drain$VARIANT$armv81 + 260 (inline_internal.h:2589)
16  libdispatch.dylib             	0x0000000185e6701c _dispatch_lane_invoke$VARIANT$armv81 + 456 (queue.c:3862)
17  libdispatch.dylib             	0x0000000185e70808 _dispatch_workloop_worker_thread + 692 (queue.c:6590)
18  libsystem_pthread.dylib       	0x00000001cbfbf5a4 _pthread_wqthread + 272 (pthread.c:2194)
19  libsystem_pthread.dylib       	0x00000001cbfc2874 start_wqthread + 8

**Comment by emawby** [comment] 2020-12-18 20:14
Closing as duplicate of #806 if you would like to move this stack trace to that issue please do so

**Closed by emawby** 2020-12-18 20:14 UTC
Labels: Beta
