### ISSUE TITLE
-[OSInAppMessage initWithCoder:]: unrecognized selector sent to instance - [OneSignalUserDefaults getSavedCodeableDataForKey:defaultValue:]

### ISSUE THREAD

**Issue by shivam-urbanyogi** [OneSignal/OneSignal-iOS-SDK#1003] opened 2021-09-24 15:06 UTC
**Description:**

1. Upgraded one signal to 3.8.0 for our iOS app.
2. Push app in the production
3. Crashing when user taps on push notification and then keep crashing on app open.

**Environment**
1. iOS SDK - 3.8.0 
2. How did you add the SDK to your project  - Cocoapods - pod 'OneSignal', '>= 3.0.0', '< 4.0'
3. XCode - 12.5.1

**Steps to Reproduce Issue:**

1. Install iOS SDK version 3.8.0 with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. User received the push notification and when taps on it app crashed. And then keep crashing on every app open

(crash stacktraces, as well as any other information here)
Crashed: com.google.firebase.crashlytics.ios.exception
0  UrbanYogi                      0x102f3f044 FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
1  UrbanYogi                      0x102f3f424 FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
2  UrbanYogi                      0x102f35e8c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  UrbanYogi                      0x102f31de8 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              0x187fcf81c _dispatch_client_callout + 20
5  libdispatch.dylib              0x187fde910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  UrbanYogi                      0x102f31594 FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  UrbanYogi                      0x102f31888 FIRCLSExceptionRecordNSException + 111 (FIRCLSException.mm:111)
8  UrbanYogi                      0x102f31178 FIRCLSTerminateHandler() + 279 (FIRCLSException.mm:279)
9  Sentry                         0x1042e0814 CPPExceptionTerminate() + 169 (SentryCrashMonitor_CPPException.cpp:169)
10 libc++abi.dylib                0x19cfccfa0 std::__terminate(void (*)()) + 20
11 libc++abi.dylib                0x19cfccf2c std::terminate() + 48
12 libobjc.A.dylib                0x19ceec91c objc_terminate + 16
13 libdispatch.dylib              0x187fcf830 _dispatch_client_callout + 40
14 libdispatch.dylib              0x187fd10b4 _dispatch_once_callout + 32
15 UrbanYogi                      0x10318b2e8 +[OSMessagingController sharedInstance] + 84 (once.h:84)
16 UrbanYogi                      0x1031accbc -[OneSignalLifecycleObserver didBecomeActive] + 87 (OneSignalLifecycleObserver.m:87)
17 CoreFoundation                 0x18833d684 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
18 CoreFoundation                 0x18833d62c ___CFXRegistrationPost_block_invoke + 52
19 CoreFoundation                 0x18833cb98 _CFXRegistrationPost + 440
20 CoreFoundation                 0x18833c558 _CFXNotificationPost + 716
21 Foundation                     0x18964345c -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
22 UIKitCore                      0x18a42180c -[_UISceneLifecycleMonitor didBecomeActive] + 348
23 UIKitCore                      0x18a422ea4 __111-[_UIWindowSceneFBSSceneLifecycleMonitor transitionToTargetState:fromState:withTransitionContext:preparations:]_block_invoke_2.117 + 124
24 UIKitCore                      0x18a994458 _UIScenePerformActionsWithLifecycleActionMask + 104
25 UIKitCore                      0x18a422d20 __111-[_UIWindowSceneFBSSceneLifecycleMonitor transitionToTargetState:fromState:withTransitionContext:preparations:]_block_invoke.116 + 180
26 UIKitCore                      0x18a432020 ___UISceneLifecycleSettingsUpdateBlockWithCanvasAndTransitionContext_block_invoke_2 + 356
27 UIKitCore                      0x18a422770 -[_UIWindowSceneFBSSceneLifecycleMonitor transitionToTargetState:fromState:withTransitionContext:preparations:] + 1080
28 UIKitCore                      0x18a431d60 ___UISceneLifecycleSettingsUpdateBlockWithCanvasAndTransitionContext_block_invoke + 368
29 UIKitCore                      0x18a433898 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 144
30 UIKitCore                      0x18a8a1e84 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 892
31 UIKitCore                      0x18a9ad268 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 276
32 UIKitCore                      0x18a4335c4 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 384
33 UIKitCore                      0x18a25b4ac __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 776
34 UIKitCore                      0x18a259e2c -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 256
35 UIKitCore                      0x18a25b0d4 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 248
36 UIKitCore                      0x18add5700 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 572
37 UIKitCore                      0x18a8cb4e4 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 388
38 FrontBoardServices             0x1979b45d8 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 440
39 FrontBoardServices             0x1979dfd44 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.200 + 128
40 FrontBoardServices             0x1979c36a4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
41 FrontBoardServices             0x1979dfa0c __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 372
42 libdispatch.dylib              0x187fcf81c _dispatch_client_callout + 20
43 libdispatch.dylib              0x187fd330c _dispatch_block_invoke_direct + 268
44 FrontBoardServices             0x197a07fa0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
45 FrontBoardServices             0x197a07c30 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 448
46 FrontBoardServices             0x197a08184 -[FBSSerialQueue _performNextFromRunLoopSource] + 32
47 CoreFoundation                 0x18835c990 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
48 CoreFoundation                 0x18835c88c __CFRunLoopDoSource0 + 208
49 CoreFoundation                 0x18835bbfc __CFRunLoopDoSources0 + 376
50 CoreFoundation                 0x188355b70 __CFRunLoopRun + 820
51 CoreFoundation                 0x188355308 CFRunLoopRunSpecific + 600
52 GraphicsServices               0x19f9d8734 GSEventRunModal + 164
53 UIKitCore                      0x18add375c -[UIApplication _run] + 1072
54 UIKitCore                      0x18add8fcc UIApplicationMain + 168
55 UrbanYogi                      0x102b60d9c main + 27 (FollowButton.swift:27)
56 libdyld.dylib                  0x188011cf8 start + 4

**Comment by emawby** [comment] 2021-09-24 17:52
@shivam-urbanyogi Hello thank you for reporting this seems similar to #996. We were not able to reproduce that crash so we modified our migration to potentially fix the issue in version 3.8.1. But, this report gives more context on the issue so if it isn't fixed in 3.8.1 I will continue investigating

**Closed** 2021-10-04 17:10 UTC
