### ISSUE TITLE
[Crash]: iOS app crashes on startup

### ISSUE THREAD

**Issue by danieRG** [OneSignal/OneSignal-iOS-SDK#1095] opened 2022-05-25 03:19 UTC
### What happened?

React Native: The app closes when it launches on the ios platform. It does not throw any error in the console, it only closes.

Installing the react-native-onesignal dependency or doing it natively causes the problem, no further action is needed.

Android platform works fine

### Steps to reproduce?

```Markdown
1.- install react-native-onesignal
2.- Or setup manually

following the documentation provided:

https://documentation.onesignal.com/docs/react-native-sdk-setup
or
https://documentation.onesignal.com/docs/ios-sdk-setup
```

### What did you expect to happen?

I hope that the ios app works correctly even if no onesignal configurations have been made

### OneSignal iOS SDK version

OneSignalXCFramework (3.11.1)

### iOS version

15

### Specific iOS version

```Markdown
* iOS 15.5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2022-05-25 15:16
@danieRG This is caused by a version discrepancy between the react-native-onesignal SDK and the OneSignalXCFramework version used in the notification service extension. We are releasing a new version of the react native onesignal sdk today that will use the latest native iOS sdk version, but in the mean-time you can force your Notification Service Extension to use version 3.10.3 of the OneSignalXCFramework

**Comment by emawby** [comment] 2022-05-25 21:35
@danieRG This should be fixed in the latest flutter version (works in my testing at least). Feel free to reopen if that isn't the case

**Closed by emawby** 2022-05-25 21:35 UTC
