### ISSUE TITLE
App startup crash

### ISSUE THREAD

**Issue by davorsafranko** [OneSignal/OneSignal-iOS-SDK#1013] opened 2021-10-19 17:36 UTC
**Description:**

App crashes on startup.
Crashlytics log:
Fatal Exception: NSInvalidUnarchiveOperationException
*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (OSInAppMessageInternal) for key (NS.objects) because no class named "OSInAppMessageInternal" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver

**Environment**

1. We are using version 3.8.1 of the OneSignal iOS SDK.
2. We added the SDK via Cocoapods.

**Steps to Reproduce Issue:**

1. Install iOS SDK version 3.8.1 with Cocoapods into a project
2. Initialize the SDK in didFinishLaunchingWithOptions:
3. Call OneSignal.setAppId
4. App crashes during init

**Comment by emawby** [comment] 2021-10-20 21:54
This is a recurrence of the issue from #996 that was attempted to be fixed by release 3.8.1. @davorsafranko Are you able to reproduce the issue since you provided reproduction steps? If so could please share a sample project with the issue since we were never able to reproduce this

**Comment by emawby** [comment] 2022-01-13 19:01
Closing for now. Please feel free to reopen if this is still occurring.

**Closed by emawby** 2022-01-13 19:01 UTC
