### ISSUE TITLE
(UNNotificationRequest - Service Extension) request.content.userInfo is serialized only when it is a rich notification, in other cases it is serialized as null

### ISSUE THREAD

**Issue by hectorvillag** [OneSignal/OneSignal-iOS-SDK#789] opened 2020-11-10 01:08 UTC
I am trying to save the data of the received notification, including the launchURL using the method
[OSNotificationPayload parseWithApns: request.content.userInfo] but the launchURL field is only filled when it is a rich notification, in case you have no image and only have the url the field ends in null, try to get it by accessing it directly using the userInfo dictionary, but in the same way it is only serialized when it is an enriched notification

**Comment by emawby** [comment] 2020-11-11 21:04
Hello I am not able to reproduce this issue when trying to read the launchUrl in the Notification Service Extension (I am assuming this is where you are trying to retrieve it?) I am receiving the launchUrl regardless of the attachments on the payload. Filling out the entire issue template would be helpful to get more context about how you are using OneSignal and why this might be happening.

**Comment by emawby** [comment] 2022-01-20 17:29
Closing for now, please feel free to reopen with more information provided!

**Closed by emawby** 2022-01-20 17:29 UTC
Labels: Need More Information, Non-Reproducible
