### ISSUE TITLE
Can't build for MacCatalyst

### ISSUE THREAD

**Issue by SwiftiSwift** [OneSignal/OneSignal-iOS-SDK#698] opened 2020-06-21 12:56 UTC
**Description:**
Hi! I tried to use OneSignal with MacCatalyst but i get this error below. Everything works if I run it on iOS.

Error:
```
ld: in /<PROJECT_PATH>/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-x86_64-master.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '<PROJECT_PATH>/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Thanks!

**Environment**
- Xcode 11.5 (11E608c)
- macOS 10.15
- OneSignal via Cocoapods (latest version)

**Steps to Reproduce Issue:**
  1. Enable Mac in your Deployment Info
  2. Install the latest OneSignal iOS SDK using Cocoapods
  3. Setup OneSignal in your NotificationExtension as shown below.
  4. Try to run your code on your Mac using macOS 10.15
  5. ERROR

**Anything else:**

I tried almost everything that was mentioned on this post https://github.com/OneSignal/OneSignal-iOS-SDK/issues/534, but nothing seem to work.
I also tried this https://onesignal.com/blog/onesignal-supports-mac-catalyst-build/

I also tried to add `x86_64h`:
![image](https://user-images.githubusercontent.com/42656134/85225166-7887f680-b3cf-11ea-98e4-d372d2116c85.png)

This is my `Podfile`:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyProjectName' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for MyProjectName
pod 'FSPagerView'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Performance'
pod 'OneSignal'

end

target 'OneSignalNotificationServiceExtension' do
  #only copy below line
  pod 'OneSignal'
end
```

**Comment by rgomezp** [comment] 2020-06-22 20:15
Duplicate of #636

**Closed by rgomezp** 2020-06-22 20:15 UTC
