### ISSUE TITLE
Please update to iOS 13 beta 3

### ISSUE THREAD

**Issue by janczakb** [OneSignal/OneSignal-iOS-SDK#505] opened 2019-07-16 08:07 UTC
ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "[\"Identifier invalid format.\"]"
    );
}}

**Comment by rgomezp** [comment] 2019-07-18 20:42
Duplicate of #504

**Closed by rgomezp** 2019-07-18 20:42 UTC
