### ISSUE TITLE
Crash sending inApp message to test devices

### ISSUE THREAD

**Issue by pclemente** [OneSignal/OneSignal-iOS-SDK#555] opened 2019-10-11 20:10 UTC
Description:

When sending an in App message to a test device, the App crashes. This issue was present in the previous version and documented in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/542

Environment

We are using the latest version of the SDK (2.11.2) installed via Cocoapods

Steps to Reproduce Issue:

Install the SDK via cocoapods
Initialise OneSignal following the documentation
Add a test device
Create an in-App message via the dashbaord and tap on "Test on preview device"
When viewing the message in the App, tap on the X to close it and the App crashes
Anything else:

this is the crash stacktrace

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1c36e498c __exceptionPreprocess
1  libobjc.A.dylib                0x1c340d0a4 objc_exception_throw
2  CoreFoundation                 0x1c35e843c -[NSOrderedSet initWithSet:copyItems:]
3  UIKitCore                      0x1c77202a8 -[UIResponder doesNotRecognizeSelector:]
4  CoreFoundation                 0x1c36e8b80 ___forwarding___
5  CoreFoundation                 0x1c36eabec _CF_forwarding_prep_0
6  MyApp                      0x1043ae530 -[OSMessagingController messageViewControllerWasDismissed] + 299 (OSMessagingController.m:299)
7  MyApp                      0x1043cc45c __72-[OSInAppMessageViewController dismissCurrentInAppMessage:withVelocity:]_block_invoke.257 + 434 (OSInAppMessageViewController.m:434)
8  UIKitCore                      0x1c7b70e84 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
9  UIKitCore                      0x1c7b45148 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
10 UIKitCore                      0x1c7b45650 -[UIViewAnimationState animationDidStop:finished:]
11 QuartzCore                     0x1ca07a4c0 CA::Layer::run_animation_callbacks(void*)
12 libdispatch.dylib              0x1c33b2184 _dispatch_client_callout
13 libdispatch.dylib              0x1c339535c _dispatch_main_queue_callback_4CF$VARIANT$armv81
14 CoreFoundation                 0x1c36623c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
15 CoreFoundation                 0x1c365d3b8 __CFRunLoopRun
16 CoreFoundation                 0x1c365c8bc CFRunLoopRunSpecific
17 GraphicsServices               0x1cd4c8328 GSEventRunModal
18 UIKitCore                      0x1c76f26d4 UIApplicationMain
19 MyApp                      0x10416b2a0 main + 23 (Tag.swift:23)
20 libdyld.dylib                  0x1c34e7460 (Falta)

**Comment by rgomezp** [comment] 2019-10-15 01:07
Duplicate of #542

**Closed by rgomezp** 2019-10-15 01:07 UTC
