### ISSUE TITLE
initWithLaunchOptions never returns

### ISSUE THREAD

**Issue by ogres** [OneSignal/OneSignal-iOS-SDK#408] opened 2018-09-04 08:46 UTC
Hello,

The problem occurs on 2.8.6, have not tried 2.8.7 yet, but the code for this has not changed.

Here is a stack-trace,

![screen shot 2018-09-04 at 10 39 44](https://user-images.githubusercontent.com/2391557/45020308-e7476480-b02e-11e8-92b3-b25032094015.png)

Here is a log:

```
Called init with app ID: xxx
TIC TCP Conn Failed [1:0x7b30000300c0]: 3:-9802 Err(-9802)
TIC TCP Conn Failed [4:0x7b3000030000]: 3:-9802 Err(-9802)
TIC TCP Conn Failed [5:0x7b30000300c0]: 3:-9802 Err(-9802)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Task <B0F290E9-5BBC-4950-8679-E523841D4F90>.<1> HTTP load failed (error code: -1200 [3:-9802])
Task <B0F290E9-5BBC-4950-8679-E523841D4F90>.<1> finished with error - code: -1200
```

After that, app freezes and does nothing. 

Looks like OneSignal checks whether device can make purchases or not, but `SKPaymentQueue` creates semaphore, makes network request, it fails and it never returns.

It does not happen every time, but still quite often.

Maybe it is a bug inside `SKPaymentQueue` , but why does OneSignal even check that? And how can I disable this feature?

**Comment by Nightsd01** [comment] 2018-09-04 16:39
Hi @ogres,

Thanks for posting this issue but it is a duplicate of #248. We do believe this is a bug with StoreKit but we plan to investigate further this week.

**Closed by Nightsd01** 2018-09-04 16:39 UTC
