### ISSUE TITLE
Apns Delegate Never Fired for some iphone

### ISSUE THREAD

**Issue by gyong0108** [OneSignal/OneSignal-iOS-SDK#503] opened 2019-06-18 11:50 UTC
Hello, Everyone.
I am developing new ios app and using onesignal.com for push notification
https://www.screencast.com/t/6sydJuE2

But I got this issue for some iphone.
some iphones are works well but something is not working.
I am not sure what is this issue.
Please help me.

**Comment by rgomezp** [comment] 2019-06-25 17:39
Hello,
Can you please paste your Podfile? 

This may be related to #180

**Comment by wilf16** [comment] 2019-06-26 03:21
Hi,

I think I was able to figure out the problem(at least on my end). 
So this is how my Podfile looks like
```
target 'MyProject' do
    pod 'Crashlytics', '~> 3.12.0'
    pod 'Fabric', '~> 1.9.0'
    pod 'MyCustomFramework', '~> 1.0.0'
    
    target 'MyCustomStaticLibrary' do
        pod 'MyCustomFramework', '~> 1.0.0'
    end
end
```

I have a static library embedded in the project that causes this similar linking problem with cocoapods [#5768](https://github.com/CocoaPods/CocoaPods/issues/5768). I think because of this problem I get this warning from OneSignal 
`WARNING: Already swizzled UIApplication.setDelegate. Make sure the OneSignal library wasn't loaded into the runtime twice!`

Because of this swizzling` application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)` fails and OneSignal can't get the PushToken even if the device is able to acquire one.

Is this correct @rgomezp ?

**Comment by rgomezp** [comment] 2019-07-08 23:25
@wilf16 ,
It's certainly possible, though I'm not 100% certain. Thanks for posting your Podfile. If you were able to resolve, maybe @gyong0108 was able as well? Please respond as I would like to close this issue if it has been resolved

**Comment by wilf16** [comment] 2019-07-09 00:42
@rgomezp yes, it did resolve the problem in swizzling between cocoa pods and a static library. Although it's not an ideal solution, but for now it will do.

**Comment by rgomezp** [comment] 2019-07-09 00:48
I will close for now. @gyong0108 please comment if you would like to reopen

**Comment by AlbertoLourenco** [comment] 2019-10-03 13:15
The problem persists in iOS 13.2.1

**Comment by mikasaloliz** [comment] 2019-10-07 08:00
im confirm that this problem persists in iOS 13.1.2

**Comment by rymesaint** [comment] 2019-10-13 10:53
i have this problem as well

**Comment by rgomezp** [comment] 2019-10-14 23:50
@mikasaloliz , @rymesaint ,
I recommend getting the full system log from Window > "Devices and Simulators" and press the "Open Console" for your device. The log should then be shared with Apple.

Also, try toggling your WIFI (see #514 )

**Comment by AlbertoLourenco** [comment] 2019-10-15 20:40
It doesn't solve the problem.

**Comment by michelalbers** [comment] 2019-10-15 22:02
Got the same issue - any help would be greatly appreciated

**Comment by rgomezp** [comment] 2019-10-15 23:46
Can you post the full log by following the steps I mentioned above?

**Comment by Luckygirlllll** [comment] 2019-10-17 09:49
I'm getting the same error  in iOS 13.1.2, I'm using react-native-oneSignal

**Comment by Luckygirlllll** [comment] 2019-10-17 10:01
I'm getting the same error  in iOS 13.1.2, I'm using react-native-oneSignal, changing wifi doesn't fix a problem

**Comment by rgomezp** [comment] 2019-10-17 18:01
@Luckygirlllll ,
Can you post the full log by following the steps I mentioned above?

Please turn on OneSignal [logging](https://documentation.onesignal.com/docs/ios-native-sdk#section--setloglevel-)

**Comment by rgomezp** [comment] 2019-10-29 21:09
Closing due to no response

**Comment by jcancinar** [comment] 2019-10-30 15:47
@rgomezp Please do not close, I have been waiting for a solution for this exact issue. Any improvements?

**Comment by Twitch247** [comment] 2019-10-30 17:11
I am also experiencing this and can provide you with any logs or outputs you require. 
onesignal-cordova-plugin 2.6.0
Xcode 11.1
iPhone Xr iOS 13.1.3

**Comment by rgomezp** [comment] 2019-10-30 18:50
Please include the full logs by following the steps I mentioned above

**Comment by Twitch247** [comment] 2019-10-30 20:24
Actually, by brute forcing it by removing the plugin and reinstalling, then updating the pod repo and re-installing the pod it fix the issue for me. However, if it reappears I will do so.

**Comment by rgomezp** [comment] 2019-10-30 21:57
@Twitch247 ,
Thanks for your solution.

@jcancinar , can you please try?

**Comment by zootopia106** [comment] 2019-10-31 19:07
Hello, i am also faced with this issue in ios13.2
Any solid solution??

**Comment by rgomezp** [comment] 2019-10-31 19:53
Can you post the full log by following the steps I mentioned above?

**Comment by musttafa** [comment] 2019-10-31 22:53
I was dealing with this problem for days. Tried many things. **Carthage**, **Pod file**, etc. And then it suddenly it worked. I couldn't realize how I did it! Then I tried to figure that out. Now I know what should I do to make it work. 

As it says "**APNS Delegate Never Fired**" in the error message, you should create **Push Certificate** again and then install on your system and then export it for  OneSignal and import. (Wrote it short because, I think you know the process)

I think the second one is really weird because that one is **WIFI**!!! When I realized that, I really get shocked! But it works and everything is fine. I stopped thinking and made my job 👍 :)

Hope this short explanation helps. Greetings...

**Comment by jcancinar** [comment] 2019-10-31 23:13
@rgomezp I have removed EVERYTHING and had a clean start of Cordova. The first plugin I added was Onesignal, it worked. Then I moved the old www files and plugins to the new Cordova project

It simply worked. I still have no idea what caused it but I can live with that.

**Comment by zootopia106** [comment] 2019-11-01 03:26
@musttafa 
i regenerated push certiciate again and then install it on onesignal
But it's still not working.

**Comment by musttafa** [comment] 2019-11-01 09:02
@zootopia106 
You use a real device to run your project and WIFI open?

**Comment by flemx** [comment] 2019-11-01 16:12
Getting the same issue since few days on all new devices.

![image](https://user-images.githubusercontent.com/10288045/68038597-3ab05380-fcc2-11e9-9b4d-953e60d633d9.png)

What I have tried to do:
-  Changed bundle Id, created a new certificate and uploaded to onesignal
-  Rebuilt the while app from scratch using the IOS setup guide

**Comment by rgomezp** [comment] 2019-11-01 20:06
Can you post the full log by following the steps I mentioned above?

**Comment by j2damax** [comment] 2019-11-04 04:27
Push notifications not working with iOS 13 with latest One Signal SDK.

Log
Called init with app ID: aae09674-5055-430a-905f-5130fb9678dc
Firing registerForRemoteNotifications
registerForPushNotifications Called:waitingForApnsResponse: 1
oneSignalApplicationDidBecomeActive
getNotificationTypes:mSubscriptionStatus: -1
oneSignalApplicationWillResignActive
network response (OSRequestGetIosParams): {
updateNotificationTypes called: 15
startedRegister: 1
oneSignalApplicationDidBecomeActive
getNotificationTypes:mSubscriptionStatus: -1
getNotificationTypes:mSubscriptionStatus: -1
oneSignalApplicationWillResignActive
oneSignalApplicationDidBecomeActive
getNotificationTypes:mSubscriptionStatus: -1
getNotificationTypes:mSubscriptionStatus: -1
Calling OneSignal create/on_session
HTTP Request (OSRequestRegisterUser) with URL: https://onesignal.com/api/v1/players, with parameters: {
network response (OSRequestRegisterUser): {
getNotificationTypes:mSubscriptionStatus: -1
 getNotificationTypes:mSubscriptionStatus: -1
oneSignalApplicationWillResignActive
HTTP Request (OSRequestOnFocus) with URL: https://onesignal.com/api/v1/players/ab10f8ea-8410-46fe-be91-d1d90455dc22/on_focus, with parameters: {
network response (OSRequestOnFocus): {
oneSignalApplicationDidEnterBackground
<img width="1430" alt="apns" src="https://user-images.githubusercontent.com/1323820/68099639-7f6a0380-fee9-11e9-9593-e86348a9da51.png">
![Uploading apns2.png…]()

**Comment by Russel1** [comment] 2019-11-04 13:03
Have you also uploaded the app to Testflight before or built it directly on the device via XCode? It works for me if I download the version from Testflight.

**Comment by flemx** [comment] 2019-11-04 14:45
@Rgomez 

I re-configured again with new certs and it is working now, not able to reproduce it anymore so cannot generate the logs.

Will get the logs if it occurs again.

**Comment by hunturkey** [comment] 2019-11-07 00:08
Make sure "Push Notifications" capability in XCode is enabled for your Target projects!
Mine were mysteriously removed when Xcode auto-updated from version 10 to version 11.2.

**Comment by rgomezp** [comment] 2019-11-07 01:08
Great to hear y'all were able to resolve. Is this safe to close?

**Comment by zootopia106** [comment] 2019-11-07 01:49
Still getting `Apns Delegate Never Fired` in the onesignal dashboard.

**Comment by rgomezp** [comment] 2019-11-07 19:23
@zootopia106 , can you re-upload your cert to the OneSignal dashboard?

**Comment by zootopia106** [comment] 2019-11-08 02:08
I could fix this problem by using cocoapods.
I was not using cocoapod when i set up onesignal into ios project.
I reconfigured it from scratch and set up coocapod, it fixed!
Thanks

**Comment by summonerriftofficial** [comment] 2019-11-14 21:11
The problem didn't fix yet,

I try all the solution above but none works

Note: it works for some mobile 

![Screen Shot 2019-11-14 at 11 10 49 PM](https://user-images.githubusercontent.com/52756966/68896415-19c11700-0734-11ea-8b01-81181968f850.png)

**Comment by niqt** [comment] 2019-11-22 08:19
Today i have this problem (from about 2 a.m. UTC +1), and i must toggle the wifi - i have also some subscription action (that i didn't)

**Comment by otkmember** [comment] 2019-12-08 06:29
I have the same trouble.
i tried all the solutions but none was helped, but i sure that a token is coming in, because i can get it via didRegisterForRemoteNotificationsWithDeviceToken.
the question is - why it not passing next to onesignal servers?

**Comment by jcancinar** [comment] 2019-12-08 12:42
I had to remove Branch.io plugin in favor of Onesignal. Now it’s working fine.

I will look for a solution again in near future because we need the Branch plugin

My suggestion to you is to remove the other plugins to see which one Onesignal doesn’t work with

**Comment by rgomezp** [comment] 2019-12-09 23:35
Can you please try @jcancinar 's suggestion? Cheers

**Comment by otkmember** [comment] 2019-12-10 01:43
well, the my problem is not in oneSignal itself, but because some conflict between Corona SDK native project  and OneSignal.
I created a [thread](https://forums.coronalabs.com/topic/76787-onesignal-problem-with-ios-native-build/) on Corona forums, where i wrote this situation more detail.
sorry for disturbing, but if you can help in my case, please do.

**Comment by jkasten2** [comment] 2019-12-10 02:16
@otkmember I followed with you on the specific Corona SDK issue on their forums.

@jcancinar With the Branch.io issue if you are seeing this Apns never fired error then the issue is most likely they are swizzling the AppDelegate incorrectly. I recommend making sure you have their latest SDK and reporting this issue to them.

**Comment by canado** [comment] 2019-12-18 21:57
I also have the same problem, but with phonegap build, any insight I can use ?
Regards

**Comment by nikiman** [comment] 2020-01-04 17:18
After losing my mind I finally found the solution: "background fetch" mode must be enabled on Signing & Capabilities tab. 

<img width="404" alt="Schermata 2020-01-04 alle 18 12 12" src="https://user-images.githubusercontent.com/2759198/71769195-2d138600-2f1e-11ea-8b17-81382f3cb87a.png">

This works on iPhone 8 with iOS 13.3 and the "APNs delegate never fired" has disappeared

<img width="970" alt="Schermata 2020-01-04 alle 18 18 35" src="https://user-images.githubusercontent.com/2759198/71769235-a9a66480-2f1e-11ea-9fa6-f86a0f517de8.png">

**Comment by caglardurmus** [comment] 2020-01-06 10:12
I am getting this error too. I am not usegin CocoaPods and my react native version 0.59.10.

**Comment by nikiman** [comment] 2020-01-06 14:54
@caglardurmus even updating the OneSignal plugin to the latest version?

**Comment by canado** [comment] 2020-01-06 15:07
@nikiman the background check is a feature in the iOS system phone?
thanks

**Comment by nikiman** [comment] 2020-01-07 08:16
@canado forgive me that I haven't specified. The **background fetch** mode must be checked on Xcode (Signing & Capabilities tab) before publishing the app.

**Comment by canado** [comment] 2020-01-07 15:08
ahh ok, because I am not using Xcode but Phonegap Build
So just to make sure, on apple's certificate website there is no such params to check / uncheck?

**Comment by jkasten2** [comment] 2020-01-09 04:25
## Issue 1 - APNS Connection
"background fetch" isn't required to register for push, the "Apns Delegate Never Fired" seems to be due to a connection issue to Apple if the problem goes away after toggling wifi or using a different network or iOS device. This might only be an issue with Apple's sandbox's servers.

To avoid splitting the conversation between multiple tickets I am closing this one in-favor of #514. Please check the device logs as noted in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/514#issuecomment-572373987 to see if this is the cause of the issue for you.

## Issue 2 - Conflicting Library
If you are consistently see the issue after trying the above then the issue is due to another library conflicting with OneSignal's Delegate method sizzling. I recommend trying to remove other libraries that support push to narrow down the issue in this case. Once you have narrowed it down to a specific library interfering please open a new ticket with the exact versions so we can reproduce the issue.

## Locking Issue
Please read the following two sections above and follow their suggestions. If nether apply please open a new issue.

**Closed by jkasten2** 2020-01-09 04:25 UTC
Labels: Help Wanted
