### ISSUE TITLE
Version 3.0.0 - Xcode Crash Reports - OneSignalNotitificationServiceExtension + 209748

### ISSUE THREAD

**Issue by idefen1** [OneSignal/OneSignal-iOS-SDK#834] opened 2020-12-16 15:16 UTC
I have now updated to the 'latest release' 3.0.0 and continue to get errors via Xcode Crash Reports, both the same error from #811 and now a slightly new error shown below: "OneSignalNotitificationServiceExtension + 209748". 

Environment
Crash Report shows crash occurring on iOS 13.6, 13.7, 14, 14.1, 14.2

Steps to Reproduce Issue:

1. Install iOS SDK 3.0.0 (Official Release) with Cocoapods into a project
1. Followed the 'upgrade' instructions
1. Tested receiving notifications with no issue on my physical device (across all cases: app open, app in background, app closed) - no issues
1. Released new app version into Production
1. Getting new Crash Reports from Apple (Organizer/Crash Reports). Partial crash report below. **OneSignalNotitificationServiceExtension + 209748**

I have written issue tickets #806 #811 and have not received any update in >28 days. Is there any additional information I can provide that would help you look into this? Any help or update would be greatly appreciated. 

Thank you.

--

Thread 1 name:
Thread 1 Crashed:
0   CoreFoundation                	0x000000019f95a3ec CFRelease.cold.1 + 16 (CFRuntime.c:1015)
1   CoreFoundation                	0x000000019f7c51b0 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 0 (NSDictionaryM.m:263)
2   CoreFoundation                	0x000000019f861934 __CFRunLoopTimerDeallocate + 44 (CFRunLoop.c:4414)
3   CoreFoundation                	0x000000019f866104 _CFRelease + 248 (CFRuntime.c:2126)
**4   ...tificationServiceExtensionB	0x00000001000f3354 0x1000c0000 + 209748**
5   ...tificationServiceExtensionB	0x00000001000fce4c +[OneSignalNotificationServiceExtensionHandler didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 236 (OneSignalNotificationServiceExtensionHandler.m:50)
6   ...tificationServiceExtensionB	0x00000001000d43b4 +[OneSignal didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 56 (OneSignal.m:2257)
7   ...tificationServiceExtensionB	0x00000001000c7f2c -[NotificationService didReceiveNotificationRequest:withContentHandler:] + 288 (NotificationService.m:20)
8   UserNotifications             	0x00000001aebb8b40 -[_UNNotificationServiceExtensionRemoteContext didReceiveNotificationRequest:withCompletionHandler:] + 456 (_UNNotificationServiceExtensionRemoteContext.m:53)
9   Foundation                    	0x00000001a0d319a0 **NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S2**

* 16 (NSXPCConnection.m:272)
10  Foundation                    	0x00000001a0b50d74 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 1744 (NSXPCConnection.m:787)
11  Foundation                    	0x00000001a0d31ac4 message_handler + 228 (NSXPCConnection.m:866)
12  libxpc.dylib                  	0x00000001e8d270e4 _xpc_connection_call_event_handler + 164 (connection.c:691)
13  libxpc.dylib                  	0x00000001e8d274a0 _xpc_connection_mach_event + 924 (connection.c:1227)
14  libdispatch.dylib             	0x000000019f4dce7c _dispatch_client_callout4 + 20 (object.m:599)
15  libdispatch.dylib             	0x000000019f4f6d2c _dispatch_mach_msg_invoke + 472 (mach.c:2443)
16  libdispatch.dylib             	0x000000019f4e3fd8 _dispatch_lane_serial_drain + 272 (inline_internal.h:2589)
17  libdispatch.dylib             	0x000000019f4f7a3c _dispatch_mach_invoke + 468 (mach.c:2765)
18  libdispatch.dylib             	0x000000019f4e3fd8 _dispatch_lane_serial_drain + 272 (inline_internal.h:2589)
19  libdispatch.dylib             	0x000000019f4e4c90 _dispatch_lane_invoke + 460 (queue.c:3862)
20  libdispatch.dylib             	0x000000019f4eed78 _dispatch_workloop_worker_thread + 708 (queue.c:6601)
21  libsystem_pthread.dylib       	0x00000001e8d00804 _pthread_wqthread + 276 (pthread.c:2207)
22  libsystem_pthread.dylib       	0x00000001e8d0775c start_wqthread + 8

**Thread 1 crashed with ARM Thread State (64-bit): ... Address size fault**

**Comment by emawby** [comment] 2020-12-18 20:13
Hello marking this as a duplicate of #806 if you would like to move this stack trace to that issue as well please do so

**Closed by emawby** 2020-12-18 20:13 UTC
