### ISSUE TITLE
I also have problems with OneSignal and Catalyst

### ISSUE THREAD

**Issue by sabiland** [OneSignal/OneSignal-iOS-SDK#550] opened 2019-10-04 10:34 UTC
Latest OneSignal SDK (cocoapods)
Xcode 11

I also have the same issue with OneSignal and Catalyst.

```
ld: in /Users/sabiland/Library/Mobile Documents/com~apple~CloudDocs/SabilandICloudGIT/InnerTempo/InnerTempo/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-x86_64-master.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/sabiland/Library/Mobile Documents/com~apple~CloudDocs/SabilandICloudGIT/InnerTempo/InnerTempo/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by valeriologiudice** [comment] 2019-10-09 11:00
Hello everyone, I'm having this very issue as well. As reported also in this closed task https://github.com/OneSignal/OneSignal-iOS-SDK/issues/534#issue-494036891
Removing and adding OneSignal again via cocoapod didn't help, as suggested in the closed task above. Please advice. Best, Valerio.

**Comment by isaac-computer** [comment] 2019-10-11 17:13
+1 Also having this issue

**Comment by matthewdanaher** [comment] 2019-10-11 18:30
I've had to disable oneSignal from my macOS app framework while this is being solved.

**Comment by valeriologiudice** [comment] 2019-10-13 15:59
> I've had to disable oneSignal from my macOS app framework while this is being solved.

How can I disable it only for macOS? Do you use cocoapods? @matthewdanaher

**Comment by matthewdanaher** [comment] 2019-10-13 16:03
I did use cocoapods when building the iOS version, so I had to remove One Signal from the pod file and add the framework manually. Then under frameworks I set One Signal to iOS only instead of MacOS + iOS. Finally, I had to go into each view controller and place #if!targetenvironment(macCatalyst) import OneSignal #endif around each section where one signal was being called.

**Comment by rgomezp** [comment] 2019-10-29 18:53
Duplicate of #534

**Closed by rgomezp** 2019-10-29 18:53 UTC
Labels: Bug: Not OneSignal, Compatibility Issue
