### ISSUE TITLE
OneSignalServiceExtension failing when submitting to App Store

### ISSUE THREAD

**Issue by yusuftor** [OneSignal/OneSignal-iOS-SDK#1041] opened 2022-01-24 23:26 UTC
**Description:**

I have added OneSignal as a Swift Package and set it up as it says on your website. Now when I build and submit to the App Store it comes back with these errors:

```
[!] Error uploading ipa file: 
 [Transporter Error Output]: ERROR ITMS-90685: CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.onesignal.OneSignal-Dynamic' under the iOS application 'MyApp.app'.
[Transporter Error Output]: ERROR ITMS-90205: Invalid Bundle. The bundle at 'MyApp.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed nested bundles.
[Transporter Error Output]: ERROR ITMS-90206: Invalid Bundle. The bundle at 'MyApp.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed file 'Frameworks'.
[Transporter Error Output]: Return status of iTunes Transporter was 1: ERROR ITMS-90685: CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.onesignal.OneSignal-Dynamic' under the iOS applicati\nERROR ITMS-90205: Invalid Bundle. The bundle at 'MyApp.app/PlugIns/OneSignalNoti\nERROR ITMS-90206: Invalid Bundle. The bundle at 'MyApp.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed file 'Frameworks'.
[Transporter Error Output]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

**Environment**
1. What version of the iOS SDK are you using? iOS 15 (latest)
2. How did you add the SDK to your project (eg. cocoapods) Swift Package Manager

**Steps to Reproduce Issue:**

1. Archiving and then validating the app submits it and returns with these errors. Builds fine and runs on device but errors occur when submitting to App Store. Also tried submitting with Fastlane, and the same thing happens.

**Anything else:**

In the NotificationExtension it's including the framework OneSignal. I think this is the source of the errors. But if I remove it it complains that it can't build the NotificationService inside the extension! There doesn't seem to be a way to not embed packages installed via Swift PM. If someone can tell me how to solve this I'd greatly appreciate it! Surely I can't be the only one?

**Comment by mmonikas** [comment] 2022-01-25 12:48
You're not the only one. I'm having the same problem - added OneSignal with SPM and getting the exact same error: "Invalid Bundle. The bundle at 'MyApp.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed nested bundles." 
I've tried out some solutions found on other websites (for example here  https://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr?lq=1 or adding some run script to the app build phase like here: https://stackoverflow.com/a/68714821 ) but nothing works. Hope to get some help on it 🙏

**Comment by yusuftor** [comment] 2022-01-25 12:53
Okay I just solved this (at least it builds and submits to the app store). Basically I deleted the OneSignal framework from the Frameworks section of the extension. Then in build settings for the extension, I searched for "Runpath search paths", and I deleted all the options except `@executable_path/../../Frameworks`. That then works

**Comment by mmonikas** [comment] 2022-01-25 13:02
Thank you for your answer @yusuftor ! I wonder if OneSignal framework should be added in the Frameworks section for the main app target then? At some point before I had this framework added only for the main app target and not for the extension and the app was building fine but it would crash on start throwing some error.

**Comment by yusuftor** [comment] 2022-01-25 13:03
Yeah just for the main app target.

**Comment by yusuftor** [comment] 2022-01-26 13:32
This issue came back to me just after changing the build version of my extension. I think it must be to do with caching. I had to add in OneSignal to the extension, build it and receive the error from the App Store, then remove OneSignal from the extension and resubmit. Weird. Someone from OneSignal please sort this?

**Comment by mGraczkowskiDigitalforms** [comment] 2022-01-26 17:43
I have the same issue. I checked all the solutions and I got a bug every time:
- remove the framework from extension (can't build the NotificationService inside the extension!)
- adding some run script to the app build phase like 

`Invalid Bundle. The bundle at '.app/PlugIns/.appex' contains disallowed nested bundles.`

`CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.onesignal.OneSignal-Dynamic'`


Has anyone found a solution?

**Comment by tyler125brown** [comment] 2022-01-28 00:49
Yes, honestly such a pain! We started using one signal like 5 days ago and we are already at a breaking point. @gdeglin. @ jkasten2. We are on a timeline and not being able to submit our builds easily due to one signal is causing problems.

**Comment by jmadler** [comment] 2022-01-28 01:23
Hey folks, I understand the pain.  We'll get back to you by tomorrow morning at the earliest.

**Comment by emawby** [comment] 2022-01-28 01:26
Hello this seems like a duplicate of this issue from the [OneSignal-XCFramework repo](https://github.com/OneSignal/OneSignal-XCFramework/issues/10). If you are **NOT** using the XCFramework version of the Swift Package please let me know since it would be a different issue.

**Comment by mGraczkowskiDigitalforms** [comment] 2022-01-28 06:45
@tyler125brown I just used Carthage and it works. I didn't have time to wait to get it fixed

**Comment by yusuftor** [comment] 2022-01-29 15:53
@jmadler Any update on this?

**Comment by emawby** [comment] 2022-01-31 17:37
@yusuftor Hello we have submitted a bug report to Apple/the Swift forums but this is an issue for including any third party XCFramework in an extension at the moment. The workaround you mentioned of having the extension search paths look in the main app targets frameworks directory is the workaround we are recommending. I am updating the setup documentation to reflect that. I am going to close this issue in favor of the duplicate issue on the [XCFramework repo here](https://github.com/OneSignal/OneSignal-XCFramework/issues/10)

**Closed by emawby** 2022-01-31 17:37 UTC

**Comment by mortenholmgaard** [comment] 2022-02-04 07:49
@emawby is there a link to the Apple bug report we can follow on this?
