### ISSUE TITLE
SPM version of OneSignal weights 500MB

### ISSUE THREAD

**Issue by ksloginov** [OneSignal/OneSignal-iOS-SDK#721] opened 2020-08-10 09:40 UTC
**Description:**
Swift package for OneSignal is at least 10 times bigger than any other package I've ever seen.
Looking deeper, it's `.git` folder, that weights almost 400MB.
`pack-3bfa9dd8c5f1e3fe6557fe005f965e476dd198bc.pack` file - is absurdly inflated.

It makes code-checkouts & resetting of the cache unnecessary long

**Environment**
Release: 2.15.1
Xcode: 12

**Steps to Reproduce Issue:**

1. Add OneSignal as a Swift Package to your project
1. Go to Xcodes' Derived data -> SourcePackages -> checkouts -> OneSignal-iOS-SDK

**Anything else:**
![](https://user-images.githubusercontent.com/1670172/89769696-e1513c80-dafd-11ea-90a9-c254e342b1fe.png)
![](https://user-images.githubusercontent.com/1670172/89769689-df877900-dafd-11ea-98d4-b69d070da777.png)

**Comment by jkasten2** [comment] 2020-08-10 23:26
@ksloginov This iOS OneSignal github repo has been around for more than 5 years and contains a lot of history and binaries for each release to support Cocoapods which contributes to the large size.

There was an ask a while back to use a git clone depth of 1 on Swift's bug tracker. 
https://bugs.swift.org/browse/SR-3313

It has been marked as "Won't Do" with the following as the reason.
"... SwiftPM will clone the entire repository which is preferable by github."

However I don't believe they account for lager repos like this one so I have left the following comment.
https://bugs.swift.org/browse/SR-3313?focusedCommentId=58042&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-58042

I recommend watching their issue and some leaving a comment to get SwiftPM to reconsider.

**Comment by lawgimenez** [comment] 2020-08-11 03:54
pod 'OneSignal', '2.15.1' is not working

**Comment by jkasten2** [comment] 2020-08-11 23:13
@lawgimenez This issue's topic is on the size of this SDK as a SwiftPM.
Since you are having a setup issue with Cocoapods please open a new issue with the full error and details on reproducing the issue.

**Comment by rgomezp** [comment] 2020-08-20 20:49
Closing due to no response.

**Comment by ksloginov** [comment] 2020-12-06 19:53
The problem is still real. Lately, it takes about 40-50 minutes to download OneSignal's package. Other packages got slow too, but all 10 other packages in total take less than 2 minutes, so the difference with OneSignal is absolutely dramatic.

**Comment by brunomunizaf** [comment] 2021-01-19 21:58
Issue still exists on 3.1.0 - 570.9 MB for 545 items.

**Comment by emawby** [comment] 2021-01-21 20:02
We are in the process of fixing this by distributing the SDK as a binary via SwiftPM. This requires Xcode 12 so we are creating a new repo "OneSignal-XCFramework" that will be used just for Xcode 12+ SwiftPM. If you are on Xcode 11 you will need to continue to use this repo.

**Comment by saltyskip** [comment] 2021-05-06 07:56
Any updates on onsignal-xcframework?

**Comment by emawby** [comment] 2021-08-05 23:49
@saltyskip sorry for missing this yes the XCFramework is available as a Swift Package. The GitHub repository is [here](https://github.com/OneSignal/OneSignal-XCFramework)

**Closed by emawby** 2021-08-05 23:49 UTC
