### ISSUE TITLE
Catalyst App on Apple M1 (arm64) 

### ISSUE THREAD

**Issue by TonyVie** [OneSignal/OneSignal-iOS-SDK#864] opened 2021-01-27 13:13 UTC
**Description:**

The current xcframework of OneSignal includes only the x86_64 build for catalyst, but not the arm64. As I understand it, catalyst need specific builds for each architecture.

**Environment**

Build an ios app on a catalyst target.

**Steps to Reproduce Issue:**

**Anything else:**
Following this answer https://github.com/OneSignal/OneSignal-iOS-SDK/issues/534#issuecomment-571850786
"Closing as Catalyst is now supported, however limited to x86_64h. Please open a new issue if there are any other Catalyst issues."

**Comment by halpz** [comment] 2021-02-17 12:07
this is still broken for simulators on M1 macs

**Comment by jasperblues** [comment] 2021-02-27 01:28
I still can't build for iOS simulator, without excluding ARM64 for Simulator builds. And I have not enabled Mac Catalyst.

**Comment by emawby** [comment] 2021-03-11 18:28
@halpz @jasperblues confirming that you are both using the XCFramework version of the SDK? Are you able to reproduce this on fresh projects as well?

**Comment by jasperblues** [comment] 2021-03-11 23:11
@emawby no, I'm using `OneSignal` default version, with `use_frameworks!`. Like this: 

```ruby
target 'Fractal' do
  install_main_pods
  pod 'OneSignal', '3.2.1'
end
```

I had no idea that `OneSignalXCFramework` existed. Will try and report results. 

> Are you able to reproduce this on fresh projects as well?

I was able to repro on a fresh project. I can send a sample.

**Comment by jasperblues** [comment] 2021-03-11 23:42
@emawby Can confirm that I just wasted time checking: 

* OneSignalXCFramework is not listed anywhere in the docs. 
* It did not work for me upon installation. Is there a working reference app for M1 macs? 
* Installing version `3.2.3` of the `OneSignal` pod doesn't solve the issue. Same symptoms as 3.2.1

**Comment by emawby** [comment] 2021-03-12 00:11
> @emawby Can confirm that I just wasted time checking:
> 
> * OneSignalXCFramework is not listed anywhere in the docs.
> * It did not work for me upon installation. Is there a working reference app for M1 macs?
> * Installing version `3.2.3` of the `OneSignal` pod doesn't solve the issue. Same symptoms as 3.2.1

Hello I apologize for the difficult to navigate documentation. The documentation on XCFrameworks is [here](https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst) and I have updated the setup page to mention Apple Silicon Macs. The OneSignal Cocoapod uses a standard framework which cannot support multiple architectures for the same build target so you will need to use the OneSignalXCFramework Cocoapod

**Comment by jasperblues** [comment] 2021-03-12 00:59
@emawby I tried exactly the above steps, upgrading an existing project. The result is: 

![image](https://user-images.githubusercontent.com/430321/110875683-0ebecc80-8311-11eb-92eb-b12ebdcb4b26.png)

I just tried again and confirmed same results. 

I'll try again later on a clean sample project. Meanwhile, is there a reference application for the above?

**Comment by jasperblues** [comment] 2021-03-24 00:31
I never got CocoaPods (xcframework or standard) to install. I was able to build from source. What I did: 

* Check out the project
* Change the mach-o type from DynamicLibrary to static. (Dynamic never worked on device). 

![image](https://user-images.githubusercontent.com/430321/112236227-05bbec80-8c7b-11eb-9f24-9519c5e0c073.png)

* Use this script to build: 

```
#!/bin/bash

rm -fr build

mkdir -p build/device
mkdir -p build/simulator
mkdir -p build/simulator_arm64
mkdir -p build/universal

rm -fr ./OneSignalFramework.framework

rm -fr ~/Library/Developer/Xcode/DerivedData/

xcodebuild -project OneSignal.xcodeproj -sdk iphoneos -target OneSignalFramework BUILD_LIBRARY_FOR_DISTRIBUTION=YES

rm -fr ~/Library/Developer/Xcode/DerivedData/

rm -fr ./OneSignal.framework
xcodebuild -project OneSignal.xcodeproj ARCHS=arm64 ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator -target OneSignalFramework BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild -quiet -create-xcframework \
	-framework "build/Release-iphoneos/OneSignal.framework" \
	-framework "build/Release-iphonesimulator/OneSignal.framework" \
	-output "build/universal/OneSignal.xcframework"

```

^-- That's for simulator+arm64 and device. (Could probably add in simulator+x86). 

Finally like that it worked, and now since I don't need to run the simulator via Rosetta, I can debug on AppCode, which is my preferred IDE (despite that it has a bug preventing debugging on Rosetta and despite that it eats gigabytes of RAM).

**Comment by gwijaya94** [comment] 2021-04-22 02:39
> @emawby I tried exactly the above steps, upgrading an existing project. The result is:
> 
> ![image](https://user-images.githubusercontent.com/430321/110875683-0ebecc80-8311-11eb-92eb-b12ebdcb4b26.png)
> 
> I just tried again and confirmed same results.
> 
> I'll try again later on a clean sample project. Meanwhile, is there a reference application for the above?

does it mean that we must include OneSignal pod too?

**Comment by jasperblues** [comment] 2021-04-22 03:07
@gwijaya94 For my setup I need to run in arm64 (m1 mac) simulator. I can't run through Rosetta (for a few other reasons). 

So what I did is compile my own framework like in the script in the comment (from myself - @jasperblues ) above. 

This works for me. 

Using a pod also works if you are happy to run use an Intel iOS simulator (eg through Rosetta on m1 mac). In theory Pods+m1 macs works too (according to docs, etc) however I wasn't able to get it to work.

**Comment by emawby** [comment] 2021-05-25 19:21
@gwijaya94 can you show your podfile? Does the NotificationServiceExtension target also include the OneSignalXCFramework?

**Comment by dandepeched** [comment] 2021-07-02 06:50
I simply replaced "OneSignal" with "OneSignalXCFramework" in Podfile and did pod update. Now I'm able to run project on simulator.

**Comment by emawby** [comment] 2021-08-05 23:44
Closing this issue. If you are still having issues feel free to repoen

**Closed by emawby** 2021-08-05 23:44 UTC
