### ISSUE TITLE
We don't use CocoaPods. How do I update to use the latest SDK?

### ISSUE THREAD

**Issue by dwhipps** [OneSignal/OneSignal-iOS-SDK#532] opened 2019-09-10 18:26 UTC
Tried cloning the tagged repo from 2.11.0 and replacing my existing copy of the framework with the contained OneSignal.framework, but XCode (my project) complains about not finding .o files at paths with "mikechoch" in them.

Is there no way to just provide pre-compiled frameworks?

**Comment by Nightsd01** [comment] 2019-09-10 18:59
Hey @mikechoch are you using the `build_fat_framework.sh` script to generate the frameworks? I left some details in the wiki on the process

**Comment by mikechoch** [comment] 2019-09-10 20:41
@Nightsd01 The `build_fat_framework.sh` was added as a **Run Script** to the `OneSignal-Static-Framework` and `OneSignal-Dynamic-Framework` so when you **Build** for each in Xcode, shouldn't that run the script and generate the frameworks?

**Comment by Ariandr** [comment] 2019-09-11 11:32
@dwhipps It prints the same warnings (not finding .o files) even in the Cocoapod version. It's here: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/525

**Comment by rgomezp** [comment] 2019-09-11 18:50
Duplicate of #525

**Closed by rgomezp** 2019-09-11 18:50 UTC
