### ISSUE TITLE
Sometimes push notification badge count is disappearing 

### ISSUE THREAD

**Issue by lakshmanasattineediutu** [OneSignal/OneSignal-iOS-SDK#786] opened 2020-11-05 05:46 UTC
**Description:**
Sometimes Push Notification Count(badge count) and push notification banner in lock screen are
![](https://user-images.githubusercontent.com/56586320/98070727-b457c000-1e87-11eb-8965-f259c53ab0ad.png)
 disappearing when App Instance is closed and phone in Unlocked. If i restart my iPhone again badge count is appearing after sometime again getting the same issue. 

**Environment**

1.  iOS13.7 and iOS14 also tested 
1. Cocoapods
1. Xcode 11.7

**Steps to Reproduce Issue:**

1. Install iOS SDK version 2.15.3 with Cocoapods into a project
1. Initialize the SDK in didFinishLaunchingWithOptions:
1. Attempt to receive a push notification
1. clear the app instance still phone is unlock
1. received a push notification
1. I can able see the push banner but I am unable to see the badge count(
![](https://user-images.githubusercontent.com/56586320/98070694-a1dd8680-1e87-11eb-9c2c-5c06ed374232.png)
its coming first immediately disappearing)
1.  after restart my phone I can able to see the badge count after some time again getting the same issue.

**Comment by emawby** [comment] 2020-11-06 18:37
Are you using the "increase by" or "set to" option for the badge count?

**Comment by lakshmanasattineediutu** [comment] 2020-11-09 04:18
Hi emawby thanks for ur quick response
here is my my payload for push notification in backend
{"app_id":"myapplicationid","contents":{"en":"Test notification"},"headings":{"en":"Notification from One Signal"},"ios_sound":"master_card_chime.wav","ios_badgeType":"SetTo","ios_badgeCount":9,"content_available":true,"mutable_content":true,"include_player_ids":["player_id"],"android_channel_id":"android_channel_id","data":{"ActionType":"PRM","BadgeCount":"1","GUID":"2174,GUIDMessage","Requester":"CARD"}}

**Comment by emawby** [comment] 2020-11-11 21:06
Hello I am not able to reproduce this issue can you clarify what you mean by:
3. Attempt to receive a push notification
Are you receiving a push, not tapping it, then immediately force quitting the app?

**Comment by lakshmanasattineediutu** [comment] 2020-11-12 10:04
Hello Elliot Mawby,
Yes I am receiving the push notification still app is not in background(app instance has cleared) and app is not locking also . 
Here I attached the video for better understanding. Issue is getting sometimes not always . 
I have simulate push notifications from postman multiple times than this issue came into picture.

[RPReplay_Final1600166080.MP4.zip](https://github.com/OneSignal/OneSignal-iOS-SDK/files/5529680/RPReplay_Final1600166080.MP4.zip)

**Comment by emawby** [comment] 2020-11-13 21:03
I am seeing this sometimes too but it seems to be an Apple OS bug. Do you always need to fully restart your phone? For me I can just swipe to a different page on the home screen and come back and the badge is there

**Comment by emawby** [comment] 2022-01-20 17:24
Closing this for now. Please feel free to reopen if this is still a problem and more information can be provided

**Closed by emawby** 2022-01-20 17:24 UTC
Labels: Need More Information, Bug: Not OneSignal
