### ISSUE TITLE
v2.5.7 crash: invalid type in JSON write (__NSMallocBlock__)

### ISSUE THREAD

**Issue by hixfield** [OneSignal/OneSignal-iOS-SDK#322] opened 2017-12-27 07:37 UTC
I am using carthage and v2.5.7, I get multiple crashes in the simulator AND production with "invalid type in JSON write (__NSMallocBlock__)" 

1 libobjc.A.dylib objc_retain + 147872
2 CoreFoundation +[__NSDictionaryM __new:::::] + 64132
3 CoreFoundation +[NSDictionary dictionaryWithObjectsAndKeys:] + 103964
4 OneSignal 4316317700 + 51204
5 libdispatch.dylib _dispatch_call_block_and_release + 4228
6 libdispatch.dylib _dispatch_client_callout + 4164
7 libdispatch.dylib _dispatch_queue_serial_drain$VARIANT$mp + 44612
8 libdispatch.dylib _dispatch_queue_invoke$VARIANT$mp + 47060
9 libdispatch.dylib _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 49660
10 libdispatch.dylib _dispatch_workloop_worker_thread$VARIANT$mp + 83100
11 libsystem_pthread.dylib _pthread_wqthread + 4044

attached
![invalidjsonwrite_prod_1](https://user-images.githubusercontent.com/9302613/34374378-2bb6ed2a-eae1-11e7-8796-e6b6648f7b7a.png)
![invalidjsonwrite_simul_1](https://user-images.githubusercontent.com/9302613/34374379-2bcde016-eae1-11e7-8455-50c407ed45e9.png)

 screenshots from the debugger in the simulator and the google crash analytics in production.

**Comment by Nightsd01** [comment] 2017-12-27 15:43
Hi @hixfield 

I'm sorry to see you're having this issue. I'm having a hard time reproducing it. 

Do you still encounter this issue in the latest 2.6.0 release?

During registration, data (like the build number, SDK type, whether the device is jailbroken, etc) is sent to OneSignal for your analytics and it appears that one of these properties is invalid JSON.

In the next release we will be checking to make sure the JSON is valid, and if it isn't, printing out an error to the console with the offending property.

**Comment by hixfield** [comment] 2017-12-27 16:10
I have upgraded to 2.6.0 this morning and during development I got a slightly different error now (I get it multiple times) but still pointing to the registration process and in this case I managed to get some more info, see screenshot. It seams that deviceModel is nil when trying to assemble the dataDict. I checked in the systemInfo.machine and this had a value, its like the stringWithCString is producing a nil value... It might be a good idea to verify all data values for nil before inserting them into the dict?
![devicemodelnil](https://user-images.githubusercontent.com/9302613/34386393-b994f956-eb28-11e7-825e-4de4222c2f81.png)
.

**Comment by Nightsd01** [comment] 2017-12-27 18:50
@hixfield That’s correct, I plan to add JSON validation in the next release. The registration process has been slightly refactored in 2.6.0 but not in a way that would help with this bug. 

I’ll fix this today and we’ll see if we can put out a new update to fix this tomorrow (as well as a few minor things). 

Strange that the device model is nil. Did not expect to see that!

Thank you for reporting this bug and I’ll get back with you shortly.

**Comment by hixfield** [comment] 2017-12-30 19:43
@Nightsd01 thanks on the fast reply/response. How is it going with the release? Any idea about expected release date?

**Comment by Nightsd01** [comment] 2017-12-31 05:30
Hey @hixfield, sorry for the slow response due to the holidays. I’ll fix the issue tomorrow, and I’ll try to put out a new release as soon as possible! Happy new year

**Comment by hixfield** [comment] 2017-12-31 17:45
@Nightsd01 thanks; happy new year!

**Comment by Nightsd01** [comment] 2018-01-02 21:38
Hey @hixfield , we've fixed this issue and merged the PR, please let me know if you experience any further problems and I'd be happy to help. We will be putting it out in an official release soon.

**Closed by Nightsd01** 2018-01-02 21:38 UTC

**Comment by hixfield** [comment] 2018-01-03 18:21
Thanks a lot @Nightsd01, I have switched to this build and will let you know if I encounter anymore issues!
