### ISSUE TITLE
App Store Rejection - Invalid Sdk Value - OneSignal

### ISSUE THREAD

**Issue by ertasahmet** [OneSignal/OneSignal-iOS-SDK#994] opened 2021-09-11 21:25 UTC
**Description:**

Hi,
I make an app and use OneSignal for push notifications. Now I'm trying publish my app to the App Store but I'm getting error because of OneSignal.
Error in below. I checked deployment target for OneSignal and it is IOS 13.0. There is no setting about IOS 15.0  
How can I change the sdk value?
Thank You!

------------------------------------
Dear Developer,

We identified one or more issues with a recent submission for App Store review for your app, "Giga Tacos" 1.0.1 (2). Please correct the following issues, then upload again.

ITMS-90512: Invalid sdk value - The value provided for the sdk portion of LC_VERSION_MIN_IPHONEOS in GigaTacos.app/Frameworks/OneSignal.framework/OneSignal is 15.0 which is greater than the maximum allowed value of 14.7.

Best regards,

The App Store Team

------------------------------------

**Comment by emawby** [comment] 2021-09-13 16:10
@ertasahmet Hello, this appears to be a duplicate of #986 which was a bug with version 3.6.2 and should be fixed in OneSignal version 3.7.0. If it is not fixed in version 3.7.0 please let me know and reopen the issue!

**Closed by emawby** 2021-09-13 16:10 UTC
