### ISSUE TITLE
synchronously download the image error report a crash message to apple!

### ISSUE THREAD

**Issue by a455455b** [OneSignal/OneSignal-iOS-SDK#325] opened 2018-01-05 11:36 UTC
When we send an attachment, we often receive the collapse of Apple's feedback, which usually happened here:

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  1

Last Exception Backtrace:
0   CoreFoundation                	0x185b61d04 __exceptionPreprocess + 124 (NSException.m:166)
1   libobjc.A.dylib               	0x184db0528 objc_exception_throw + 56 (objc-exception.mm:521)
2   CoreFoundation                	0x185b61c4c +[NSException raise:format:] + 116 (NSException.m:141)
3   Foundation                    	0x1864f2b94 _NSFileHandleRaiseOperationException + 160 (NSFileHandle.m:82)
4   Foundation                    	0x1864f3504 -[NSConcreteFileHandle writeData:] + 204 (NSFileHandle.m:728)
5   OneSignalNotificationServiceExtension	0x10415abc4 -[DirectDownloadDelegate connection:didReceiveData:] + 124 (OneSignalHelper.m:83)
6   CFNetwork                     	0x186339d48 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 60 (NSURLConnectionInternal.mm:124)
7   CFNetwork                     	0x186339cec -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 204 (NSURLConnectionInternal.mm:121)
8   CFNetwork                     	0x186339e60 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 56 (NSURLConnectionInternal.mm:139)
9   CFNetwork                     	0x1862f507c _NSURLConnectionDidReceiveData(_CFURLConnection*, __CFData const*, long, void const*) + 80 (NSURLConnectionInternalConnection.mm:180)
10  CFNetwork                     	0x18624089c ___ZN27URLConnectionClient_Classic29_delegate_didReceiveDataArrayEv_block_invoke + 256 (URLConnectionClient.cpp:2020)
11  CFNetwork                     	0x18623f9d0 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 108 (URLConnectionClient.cpp:0)

it like a handle exception ,Whether to consider the network timeout Or i/o operation  crash ?
I think  more judgments may be useful .
thank you for help me !

**Comment by Nightsd01** [comment] 2018-01-05 19:21
Hi @a455455b  

Do you know when you first started getting these crash reports? What version of the OneSignal SDK are you using?

**Comment by a455455b** [comment] 2018-01-08 01:10
The first time we discovered this bug was last month when Apple gave a feedback about 250 crashes a week. The version we using is 2.5.2. Is it an unstable version?

**Comment by a455455b** [comment] 2018-01-08 01:27
I am sorry I was wrong,The version we using is 2.6.0.

**Comment by Nightsd01** [comment] 2018-01-08 03:34
Hi @a455455b

That is indeed a serious problem. What types of files are being sent? Is it possible for you to send me an example of a URL from a crash?

**Comment by a455455b** [comment] 2018-01-09 07:53
Hi @Nightsd01  some imageURL like this https://img.banggood.com/deals/edm/app/images/171111app08_b1.jpg .
I think this can happen when the file is processed for download, maybe the network timed out  or a file I / O

**Comment by Nightsd01** [comment] 2018-01-09 21:35
@a455455b 

After doing some research, it appears that the most likely cause of this problem is that some people's devices are out of free/available storage.

Unfortunately the SDK currently does not handle this situation gracefully and can crash. This will be fixed in a new update within the week. 

Have you been able to reproduce this issue on your own? Or are you only seeing it from Apple's crash reports with your users?

**Comment by a455455b** [comment] 2018-01-10 01:17
@Nightsd01  So far, we can reproduce the anomaly that the crash can not debug, but we can see that the rich text notification will become a regular notification when an exception occurs.

**Comment by Nightsd01** [comment] 2018-01-10 02:01
@a455455b  I'm sorry I am not sure I understand you, you are saying that you **can** reproduce the bug on your device?

**Comment by a455455b** [comment] 2018-01-10 02:19
I'm not sure if I've reproduced this exception, but I found  it's true that poor network and available memory reduction all make rich text notifications become common notifications.

**Comment by Nightsd01** [comment] 2018-01-17 23:54
This issue is now resolved in #327 .

Keep in mind, the only change is that the SDK is now catching the exception instead of letting it crash the entire extension. However the problem causing the exception would still remain.

I think there are several potential root causes of the issue you are witnessing:

1. The users' devices are out of space and the download cannot proceed.
2. The URL's you are sending to users are improperly formatted in some way. The image URL must be properly URL encoded and cannot contain any special characters. 
3. Perhaps poor network/low memory could also be causing the issue but I find this to be less likely. The extension downloads the image attachment directly to disk in order to avoid taking up too much memory.

Please let me know if you have any further problems @a455455b and we'd be happy to help!

**Closed by Nightsd01** 2018-01-17 23:54 UTC
