### ISSUE TITLE
iOS 14 / App Clip SDK issues

### ISSUE THREAD

**Issue by basememara** [OneSignal/OneSignal-iOS-SDK#775] opened 2020-10-21 16:57 UTC
**Description:**

I added the following to my App Clip `App`:

```swift
@main
struct MyApp: App {

    #if os(iOS)
    // For legacy SDKs
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    #endif
    
    var body: some Scene {
        ...
    }
}

#if os(iOS)
// MARK: - Legacy

class AppDelegate: NSObject, UIApplicationDelegate, NotificationPlugin {
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        OneSignal.initWithLaunchOptions(
            launchOptions,
            appId: "***",
            handleNotificationAction: nil,
            settings: [
                kOSSettingsKeyAutoPrompt: false,
                kOSSettingsKeyInAppLaunchURL: false
            ]
        )
        
        OneSignal.inFocusDisplayType = .notification

        return true
    }
}
#endif
```

When trying to upload to the App Store, I get an error:

> ITMS-90842: Invalid SDK usage - App clip uses the SDK selector 'requestAlwaysAuthorization', which is not supported. Ensure your app clip is using supported SDK features.

**Environment**

1. Version 2.15.4
2. Swift Package Manager
3. Xcode 12 / iOS 14

**Comment by basememara** [comment] 2020-10-21 18:23
I just [brute force removed the code](https://github.com/basememara/OneSignal-iOS-SDK/commit/6f3bf42dde356e35dd70a20b4efd09b48ca2927e) that accesses the location features since we don't use them, but it would probably make sense to separate the location stuff in a separate framework so everyone's not forced with App Store requirements not relevant to them.

Also, App Clip users aren't getting registered with One Signal because they aren't prompted for notification permissions, because anything less than 8 hours is not required to get permissions.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/892152/96766314-df7ee180-13a8-11eb-80c8-6c05c3496ea0.png">

**Comment by emawby** [comment] 2020-10-21 18:25
Hello App Clip support is only available in our [Major Release](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.0.0-beta2) which is currently in beta.

**Comment by basememara** [comment] 2020-10-21 18:26
Was the location issue corrected there?

**Comment by basememara** [comment] 2020-10-21 18:59
It was not corrected in v3-beta so I also had to remove the location API's. Also App Clip users are still not getting registered because notification permissions aren't required for App Clip for a certain time period. This issue should remain open until it is fixed in v3-beta at least.

**Comment by basememara** [comment] 2020-10-21 20:41
Doesn't the SDK have to handle ephemeral authorization status? I don't see that in the beta codebase.

```swift
let center = UNUserNotificationCenter.current()
center.getNotificationSettings { (settings) in {
    if settings.authorizationStatus == .ephemeral {

        // The user didn't disable notifications in the App Clip card.
        // Add code for scheduling or receiving notifications here.
        return
    }
}
```

https://developer.apple.com/documentation/app_clips/enabling_notifications_in_app_clips

**Comment by basememara** [comment] 2020-10-22 16:46
Also getting this warning in the console for my App Clip even though no background capabilities is supported on App Clips.

**Comment by basememara** [comment] 2020-10-23 16:12
More feedback: Falling back to settings when prompting the user for permissions where they've previously denied permissions does not deeplink to the App Clip's iOS settings. It just goes to the iOS settings but not the App Clip settings like it does with regular apps.

**Comment by basememara** [comment] 2020-10-23 17:05
> Doesn't the SDK have to handle ephemeral authorization status? I don't see that in the beta codebase.
> 
> ```swift
> let center = UNUserNotificationCenter.current()
> center.getNotificationSettings { (settings) in {
>     if settings.authorizationStatus == .ephemeral {
> 
>         // The user didn't disable notifications in the App Clip card.
>         // Add code for scheduling or receiving notifications here.
>         return
>     }
> }
> ```
> 
> https://developer.apple.com/documentation/app_clips/enabling_notifications_in_app_clips

Since this is not handled in the SDK, `OneSignal.getDeviceState()?.hasNotificationPermission` seems very flaky for App Clips. If I toggle the notification permissions in the App Clip, the `hasNotificationPermission` doesn't accurately reflect actual permissions. I guess since there no such thing as denied notification permissions for App Clips under 8 hrs? So there should be one more check after the denial check and check if it `.ephemeral` which should return true for `hasNotificationPermission`.

**Comment by emawby** [comment] 2020-10-26 18:06
@basememara I apologize this functionality is in the major_release_3.0.0 branch but did not make it into the major release beta cut 2. That is my mistake, it will be available in the next cut of the beta! If you want to test it now you can link against the major_release_3.0.0 branch

**Comment by basememara** [comment] 2020-10-27 16:14
Thank you for the clarification, this branch works a lot better!

A question about `OneSignal.getDeviceState()?.hasNotificationPermission`.. if it's an App Clip and has `ephemeral` enabled, should `hasNotificationPermission` return true?

If this is not agreeable, then I would at least need to check if the user has ephemeral permissions so I can let the user know they have notifications enabled/disabled via the UI, or request permissions.

I was hoping to do something like this but `ephemeral` is missing from the permission status cases public API: `OneSignal.getDeviceState()?.notificationPermissionStatus == .ephemeral`.

**Comment by basememara** [comment] 2020-10-27 19:53
Related but may need a One Signal backend change.. App Clip users are still not getting push notifications unless explicitly requesting permissions from them, even though it is not needed for App Clip users and <8hrs.

![image](https://user-images.githubusercontent.com/892152/97354880-71d12a80-186c-11eb-80bf-1177fbd4f1c5.png)

How can I "trick" the server into thinking the user granted permission already if they are already given `ephemeral` authorization?

**Comment by emawby** [comment] 2020-10-30 18:23
@basememara 
In regards to the question about `hasNotificationPermission`, it should already be returning true for ephemeral permission status. The device state sets `hasNotificationPermission` from the `OSPermissionState` `reachable` method. 
```
- (BOOL)reachable {
    return self.provisional || self.accepted || self.ephemeral;
}
```
Also there is a value for the ephemeral permission in the `notificationPermissionStatus`
```
- (OSNotificationPermission)status {
    if (self.ephemeral)
        return OSNotificationPermissionEphemeral;
```

For the dashboard issue how are you initializing OneSignal for your app clip? I am not able to reproduce this issue
![image](https://user-images.githubusercontent.com/13123372/97742060-00c68880-1aa1-11eb-902.d-2109fb5cf80a.png)

**Comment by basememara** [comment] 2020-10-30 22:43
It seems the `ephemeral` status is not `public`? I can't access it from the consumer side.

For the dashboard, did you accept the push notification system permission alert? I'm referring to an App Clip user should not see any permission alert but the OneSignal dashboard should consider them subscribed since granting permissions is not needed for App Clip users since <8hrs is sufficient for our case. If it is longer than 8 hrs, then we will prompt the user for permissions.

**Comment by emawby** [comment] 2020-11-16 22:06
@basememara which version of the beta are you on? You should see OSNotificationPermissionEphemeral in OneSignal.h. If not you are on the wrong version. And your users should be considered subscribed on the dashboard without needing to prompt I did not accept the alert and my users are considered subscribed.

**Comment by basememara** [comment] 2020-11-17 16:12
I'm using the latest `major_release_3.0.0` branch and tried the latest commit `851d67094692c4040f8c93e32b94bd61f54fb1b2`.

It seems `ephemeral` it has to be added to the Swift public API here: https://github.com/OneSignal/OneSignal-iOS-SDK/blob/6e0a4839f8510c6471023744c268163b95803f02/iOS_SDK/OneSignalSDK/SwiftPM/Public/Headers/OneSignal/OneSignal.h#L244

Also different feedback... the server is targeting user App Clip experiences using the `target-content-id` property with the invocation URL. That works, however, on the iOS side, I need to extract that `target-content-id` URL so I can deep link the user in the app from the notification tap. Otherwise, it will open the right App Clip, but it will not deep link from the home screen of the App Clip based on the URL, so I need to access it to route them properly. Can you also please expose this property on the `OSNotification`? I know I can access it through a dictionary somewhere, but this would be very handy of this object.

**Comment by basememara** [comment] 2020-11-17 16:31
I'm still getting "Never Prompted" for App Clip users with the latest `major_release_3.0.0` branch. Do I need to call `registerForPushNotifications` or an ephemeral equivalent to register, or is registration supposed to happen automatically?
![image](https://user-images.githubusercontent.com/892152/99417554-0d801480-28c8-11eb-81d0-f60779e64690.png)

**Comment by basememara** [comment] 2020-11-17 19:09
I just noticed in v3 its been renamed to `prompForPushNotifications` but still same issue. Am I looking for another API like `OneSignal.register(forProvisionalAuthorization:` but for ephemeral?

**Comment by emawby** [comment] 2020-11-17 20:55
@basememara You do not need to do anything to have the ephemeral status applied when launching the app clip if the info.plist is set up correctly you have the ephemeral permission automatically. If the user turns off the permission in settings you need to prompt for full permissions

**Comment by basememara** [comment] 2020-11-18 09:18
Yes I've had the `NSAppClipRequestEphemeralUserNotification` in the info.plist set to true already. I must be missing something, still tracking this down.

Regarding the `ephemeral` permission case, I've opened a pull request #805 which solved one of the previous issues for me.

**Comment by emawby** [comment] 2020-11-19 20:09
Ah I didn't realize you were using SwiftPM! We do not update the SwiftPM header except for releases which was causing all of these issues. If you use major release beta cut 3 you will see ephemeral permission exposed properly. I apologize for the confusion

**Comment by basememara** [comment] 2020-11-19 20:19
oh man, you think all the issues will be compile-errors, or could there be run-time issues too?

I'm fortunately in a fresh iOS14+ project and want to stay 1st party as must as possible.. if you suspect SwiftPM issue, would it be a big effort to update it so I can continue testing these bleeding edge stuff? 😛 If its all all compile-error don't worry about but run-time issue pls

**Comment by emawby** [comment] 2020-11-24 18:57
@basememara The latest beta releases should both have App Clips (cut 3 and 4) so you wouldn't need to use master branch. Are you still having issues with SwiftPM?

**Comment by basememara** [comment] 2020-11-24 19:03
I'm using beta 4 and the SwiftPM seems to be working great (no compile-error or missing APIs).

The only last issue I'm trying to resolve with our App Clip launch is still the user automatically getting subscribed without needing to prompt them. For an App Clip user, the OneSignal portal is not showing them as subscribed. It's a tough one because it's not reproducible from your side.. I must be missing something or some scenario with my setup (my Info.plist was a good guess but I've had that in).

I'm testing the App Clip through TestFlight, if you are testing an actual live App Clip maybe that can be an area of issues I'm seeing. Still trying to think what it could be.

Thanks for all the support in this, you've been super helpful and responsive!

**Comment by emawby** [comment] 2020-11-24 19:11
@basememara When the user is not shown as subscribed on the dashboard does the app have push permissions in the settings app?

**Comment by basememara** [comment] 2020-11-24 19:14
Good question, no there is no notification permission at all within the App Clip settings.

When I force the prompt, notification permissions does show up there.

**Comment by emawby** [comment] 2020-11-24 19:56
Ok that means that you have not set up the ephemeral permission correctly. You should see the push permission there when the app clip is installed no prompting should be needed. Make sure you have setup your **App Clip target's** info.plist according to [this Apple guide](https://developer.apple.com/documentation/app_clips/enabling_notifications_in_app_clips?language=objc)

**Comment by emawby** [comment] 2020-12-17 04:22
Closing

**Closed by emawby** 2020-12-17 04:22 UTC
Labels: Help Wanted

**Comment by basememara** [comment] 2020-12-19 15:40
We finally released our App Clip to the App Store and the ephemeral notifications are working as expected.

The problem was TestFlight does not implement ephemeral notifications which is why we couldn't get it to work in testing. It only works while in the App Store at this time. Hopefully Apple fixes ephemeral notifications TestFlight.

Thanks for all the great work and support with this!! 🚀
