### ISSUE TITLE
Language is set to first preferred language of device automatically on SDK init

### ISSUE THREAD

**Issue by enscope** [OneSignal/OneSignal-iOS-SDK#400] opened 2018-08-17 10:55 UTC
**Description:**
Language is reset to first preferred language of device **automatically** on application startup when using OneSignal API and calling `OneSignal.initWithLaunchOptions(..)`, which is very limiting when application supports language switching. It would be useful, if it was possible to specify an option when launching, that would suppress this behaviour or at least allow to specify language (I am aware that this second option was already an issue request before, but the first one was afaik not).

**Environment**
CocoaPods installed version 2.8.6.

**Steps to Reproduce Issue:**
1. Install iOS SDK version 2.8.6 with Cocoapods into a project
2. Initialize the SDK in didFinishLaunchingWithOptions:
3. Change language for device to one that is not preferred on device (e.g. via REST API)
4. Start the application again
5. Observe language being changed back to preferred

**Comment by Nightsd01** [comment] 2018-08-17 18:12
This is not a bug but expected behavior. We want the SDK to automatically update the user's language each time they launch the app. When you launch the SDK, it detects that the language is different so it updates it via the REST api.

If you need different behavior, I would recommend using our REST API to update it at launch. It's a bit of a pain, but currently we don't support changing the language per app.

Usually iOS recommends using the system language in apps and it's not usually advisable for each app to have their own language settings.

We might consider changing this in the future and exposing a public method to override the language - I will be leaving this issue open and marking it as a feature request.

**Comment by rgomezp** [comment] 2019-04-03 00:04
Closing issue. Note: request still under consideration

**Closed by rgomezp** 2019-04-03 00:04 UTC
Labels: improvement

**Comment by fxdave** [comment] 2021-02-14 15:35
I would be happy to see something like this:
```js
OneSignal.setLanguage('en')
```
