### ISSUE TITLE
Still cannot build for iOS Simulator on M1 mac

### ISSUE THREAD

**Issue by halpz** [OneSignal/OneSignal-iOS-SDK#885] opened 2021-02-17 12:09 UTC
when can we expect this to work? I will have to choose another product if this is not possible soon

**Comment by rgomezp** [comment] 2021-02-17 21:10
Duplicate of #864

**Closed by rgomezp** 2021-02-17 21:10 UTC

**Comment by halpz** [comment] 2021-02-21 21:08
> Duplicate of #864

these issues are both closed, but are still present

**Comment by halpz** [comment] 2021-02-21 21:10
they are also different issues, one related to intel haswell the other related to arm64 (M1)

**Comment by jasperblues** [comment] 2021-02-27 01:28
I still can't build for iOS simulator, without excluding ARM64 for Simulator builds. And I have not enabled Mac Catalyst.
