### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by smauryaakeed** [OneSignal/OneSignal-iOS-SDK#1014] opened 2021-10-27 12:56 UTC
Hi team,
I'm using OneSignal iOS SDK in our app. After long use, I'm facing again NSInvalidArgumentException in iOS SDK. It is happening on initial launch of app. The code which we have written in AppDelegate class is:

```
OneSignal.initWithLaunchOptions(launchOptions)
            OneSignal.setAppId(Constants.ThirdPartyKey.oneSignalKey)
            OneSignal.promptForPushNotifications(userResponse: { _ in

            })
self.handleOneSignalPushNotification()
```

Then, written handleOneSignalPushNotification method as:

```
OneSignal.setNotificationWillShowInForegroundHandler { notification, completion in
            print("Received Notification: ", notification.notificationId ?? "no id")
            print("launchURL: ", notification.launchURL ?? "no launch url")
            print("content_available = \(notification.contentAvailable)")
            if notification.notificationId == "example_silent_notif" {
                completion(nil)
            } else {
                completion(notification)
            }
        }
        OneSignal.setNotificationOpenedHandler { result in
            // This block gets called when the user reacts to a notification received
            let notification: OSNotification = result.notification
            if let additionalData = notification.additionalData {
                if let vendorId = additionalData["vendor_id"] as? String, let type = additionalData["type"] as? String {
                    self.showVendorPage(id: Int(vendorId), type: type)
                }
            }
        }
```

I used Cocoapods to install SDK.

`pod 'OneSignal', '>= 3.0.0', '< 4.0'

Deployment target: iOS 12+
The issue is logged via Firebase Crashlytics.
<img width="886" alt="Screenshot 2021-10-27 at 6 13 50 PM" src="https://user-images.githubusercontent.com/85090919/139068248-d59c2001-e50f-4079-8a3b-be66c4b60831.png">

`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9905c __exceptionPreprocess
1  libobjc.A.dylib                0x15f54 objc_exception_throw
2  CoreFoundation                 0x17601c +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x2e484 ___forwarding___
4  CoreFoundation                 0x2d5c0 _CF_forwarding_prep_0
5  Foundation                     0x37c98 _decodeObjectBinary
6  Foundation                     0x7dba8 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:]
7  Foundation                     0x95694 -[NSArray(NSArray) initWithCoder:]
8  Foundation                     0x37c98 _decodeObjectBinary
9  Foundation                     0x1c478 _decodeObject
10 Foundation                     0x3bd34 -[NSKeyedUnarchiver decodeObjectForKey:]
11 Foundation                     0x9e8a8 +[NSKeyedUnarchiver unarchiveObjectWithData:]
12 Akeed                          0x2a831c -[OneSignalUserDefaults getSavedCodeableDataForKey:defaultValue:]
13 Akeed                          0x26900c -[OSMessagingController init]
14 Akeed                          0x268e50 __39+[OSMessagingController sharedInstance]_block_invoke
15 libdispatch.dylib              0x3950 _dispatch_client_callout
16 libdispatch.dylib              0x51d8 _dispatch_once_callout
17 Akeed                          0x268e10 +[OSMessagingController sharedInstance]
18 Akeed                          0x262d7c +[OneSignal receivedInAppMessageJson:]
19 Akeed                          0x29a990 +[OneSignalTracker applicationForegrounded]
20 Akeed                          0x289de8 -[OneSignalLifecycleObserver didBecomeActive]
21 CoreFoundation                 0x2aee8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
22 CoreFoundation                 0xc6b9c ___CFXRegistrationPost_block_invoke
23 CoreFoundation                 0x99f54 _CFXRegistrationPost
24 CoreFoundation                 0x40d54 _CFXNotificationPost
25 Foundation                     0x1b028 -[NSNotificationCenter postNotificationName:object:userInfo:]
26 UIKitCore                      0x2d3f78 -[UIApplication _stopDeactivatingForReason:]
27 UIKitCore                      0x3fc458 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
28 UIKitCore                      0x63dacc -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
29 UIKitCore                      0x5c91f0 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
30 UIKitCore                      0x1b0044 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
31 UIKitCore                      0x27062c +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
32 UIKitCore                      0x1b1f54 _UISceneSettingsDiffActionPerformChangesWithTransitionContext
33 UIKitCore                      0x29d18c -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
34 UIKitCore                      0x725b0c __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.610
35 UIKitCore                      0x1e0d5c -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
36 UIKitCore                      0x224494 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
37 UIKitCore                      0x1adf84 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
38 FrontBoardServices             0xd110 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
39 FrontBoardServices             0x25d5c __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
40 FrontBoardServices             0xa6c4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
41 FrontBoardServices             0x10b20 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
42 libdispatch.dylib              0x3950 _dispatch_client_callout
43 libdispatch.dylib              0x73e8 _dispatch_block_invoke_direct
44 FrontBoardServices             0xbfa4 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
45 FrontBoardServices             0xb3e4 -[FBSSerialQueue _targetQueue_performNextIfPossible]
46 FrontBoardServices             0xf9f4 -[FBSSerialQueue _performNextFromRunLoopSource]
47 CoreFoundation                 0xbb030 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
48 CoreFoundation                 0xcbcf0 __CFRunLoopDoSource0
49 CoreFoundation                 0x5ff8 __CFRunLoopDoSources0
50 CoreFoundation                 0xb804 __CFRunLoopRun
51 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific
52 GraphicsServices               0x138c GSEventRunModal
53 UIKitCore                      0x51b060 -[UIApplication _run]
54 UIKitCore                      0x298b8c UIApplicationMain
55 Akeed                          0xbce0 main + 15 (AppDelegate.swift:15)
56 ???                            0x100989a24 (Missing)`

Since it is happening on repetitive basis, please help me asap.

**Comment by emawby** [comment] 2021-11-04 16:48
Seems to be a duplicate of #1013

**Closed** 2021-11-08 21:01 UTC
