### ISSUE TITLE
How to disable "Would you like to open website?" alert?

### ISSUE THREAD

**Issue by bark1n9** [OneSignal/OneSignal-iOS-SDK#852] opened 2021-01-09 14:08 UTC
Description:
Since 3.0, when a Launch URL is set on notification, OneSignal asks user if they want to open the website. Is there a way to disable this?

Environment
iOS: 3.1.0 SDK
CocoaPods

Steps to Reproduce Issue:
1- Set Launch URL when sending a notification.
2- Tap on the notification on device.
3- OneSignal will ask user "Would you like to open website?".

**Comment by bark1n9** [comment] 2021-01-11 14:55
No one?

**Comment by KestasVenslauskas** [comment] 2021-01-12 08:31
Same issue here

**Comment by rgomezp** [comment] 2021-01-13 21:03
Duplicate of #777

**Closed by rgomezp** 2021-01-13 21:03 UTC
