### ISSUE TITLE
Mac Catalyst - Swift Project - Unable to load standard library for target 'x86_64h-apple-ios13.1-macabi'

### ISSUE THREAD

**Issue by robertveringa89** [OneSignal/OneSignal-iOS-SDK#636] opened 2020-03-17 08:47 UTC
**Description:**

(your description here)

**Environment**

1. What version of the iOS SDK are you using?

* 2.12.6

1. How did you add the SDK to your project (eg. cocoapods)

* CocoaPods

**Steps to Reproduce Issue:**

1. Added Mac Catalyst support with checking the checkbox for the Target
1. Followed instructions of adding 'x86_64h' as discussed here: https://onesignal.com/blog/onesignal-supports-mac-catalyst-build/ 
1. When setting the build target to my MacBook Pro I get the follow error: Unable to load standard library for target 'x86_64h-apple-ios13.1-macabi'

**Anything else:**
If I set the build target to my iPad or to a simulator everything works fine.

**Comment by marvin-yorke** [comment] 2020-03-17 10:24
Same problem for us. @robertveringa89 which version of Xcode are you using? I'm trying 11.2.1

**Comment by robertveringa89** [comment] 2020-03-17 10:25
I'm at Version 11.3.1 (11C504). Build target is iOS 11.0

**Comment by exevil** [comment] 2020-03-17 12:35
Same here.

**Comment by jkasten2** [comment] 2020-03-18 19:12
Can you make sure you only have `x86_64h` without `x86_64` for both "Valid Architectures" and "Architectures"?
![image](https://user-images.githubusercontent.com/645861/76998027-9bf35f00-6911-11ea-9e98-895ef5521153.png)
More details in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/534#issuecomment-563431891

**Comment by robertveringa89** [comment] 2020-03-18 19:13
Yes, I did that for both

**Comment by exevil** [comment] 2020-03-18 19:19
I tried multiple times with different configurations as well.

**Comment by marvin-yorke** [comment] 2020-03-18 19:45
I've even tried leaving x86_64h the only architecture

```
ARCHS=x86_64h
VALID_ARCHS=x86_64h
```

**Comment by jkasten2** [comment] 2020-03-18 22:56
I was able to reproduce the issue with Xcode 11.3.1 on a Swift project.
Objective-C projects build without this error.

I believe the `x86_64h-apple-ios13.1-macabi` standard library is referring to the Swift standard library. I tried to search if there is a `x86_64h` build of the swift standard library for Mac Catalyst but wasn't able to find anything. It is possible there is only a `x86_64` build of this.

For reference here is the details of the exact error and the command it is running:
Error: `<unknown>:0: error: unable to load standard library for target 'x86_64h-apple-ios13.1-macabi'`

```
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
 -frontend
 -c
 -primary-file /Users/josh/Documents/repos/OneSignal-iOS-SDK/Examples/SwiftExample/OneSignalNotificationServiceExtension/NotificationService.swift
 -emit-module-path /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64h/NotificationService\~partial.swiftmodule
 -emit-module-doc-path /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64h/NotificationService\~partial.swiftdoc
 -serialize-diagnostics-path /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64h/NotificationService.dia
 -emit-dependencies-path /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64h/NotificationService.d
 -emit-reference-dependencies-path /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64h/NotificationService.swiftdeps
 -target x86_64h-apple-ios13.1-macabi
 -enable-objc-interop
 -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
 -I /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Products/Debug-maccatalyst
 -F /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Products/Debug-maccatalyst
 -F /Users/josh/Documents/repos/OneSignal-iOS-SDK/Examples/SwiftExample/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework
 -Fsystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/System/Library/Frameworks
 -application-extension
 -enable-testing
 -g
 -module-cache-path /Users/josh/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
 -swift-version 5
 -enforce-exclusivity=checked
 -Onone
 -D DEBUG
 -serialize-debugging-options
 -Xcc
 -working-directory
 -Xcc /Users/josh/Documents/repos/OneSignal-iOS-SDK/Examples/SwiftExample
 -enable-anonymous-context-mangled-names
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/swift-overrides.hmap
 -Xcc
 -iquote
 -Xcc /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-generated-files.hmap
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-own-target-headers.hmap
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-all-target-headers.hmap
 -Xcc
 -iquote
 -Xcc /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-project-headers.hmap
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Products/Debug-maccatalyst/include
 -Xcc
 -isystem
 -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/usr/include
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/DerivedSources-normal/x86_64h
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/DerivedSources/x86_64h
 -Xcc
 -I/Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/DerivedSources
 -Xcc
 -DDEBUG=1
 -Xcc
 -DCOCOAPODS=1
 -parse-as-library
 -module-name OneSignalNotificationServiceExtension
 -o /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Build/Intermediates.noindex/OneSignalDemo.build/Debug-maccatalyst/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64h/NotificationService.o
 -index-store-path /Users/josh/Library/Developer/Xcode/DerivedData/OneSignalDemo-havtxbliryjovwgdekpsihwblrun/Index/DataStore
 -index-system-modules
```


## Workaround
### Option 1 - Use Swift `x86_64` for `x86_64h` builds
It might be possible to use the `x86_64` build of Swift libraries for `x86_64h`, however we don't have the details on how or if this could be done. However it might be worth exploring.

### Option 2 - Build OneSignal-iOS-SDK locally with `x86_64`
Currently the `x86_64` archeature is being used for the iOS simulator, the simulator could be switch to use Mac Catalyst instead. To do this the `ARCHS` and `VALID_ARCHS` can be set to `x86_64` on this line
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.12.6/iOS_SDK/OneSignalSDK/build_fat_framework.sh#L19
To build on your machine you will also need to update these 2 lines to `/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild`
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.12.6/iOS_SDK/OneSignalSDK/build_fat_framework.sh#L12-L13
Lastly delete simulator references from this line
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.12.6/iOS_SDK/OneSignalSDK/build_fat_framework.sh#L40
Then you can run this script to create the OneSignal.framework file.

## Fix
The long term fix will be for OneSignal to migrate from a static framework to an XCFramework.
https://developer.apple.com/videos/play/wwdc2019/416/
These should be able to support the same CPU architecture for multiple target.

**Comment by aidev1065** [comment] 2020-03-28 05:25
Hi! I tried Option 2 and was able to build the script. However, when I take the framework and put it into my project, it says that there is no module named OneSignal. Any updates on when there's a more permanent solution for using OneSignal with Catalyst?

**Comment by SwiftiSwift** [comment] 2020-06-23 13:44
How can I build the OneSignal-iOS-SDK locally ? I'm using Cocoapods currently

**Comment by emawby** [comment] 2020-08-04 22:26
This issue is fixed by using the XCFramework version of the SDK (currently only supported via Cocoapods). Instructions for use are [here](https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst)

**Comment by SwiftiSwift** [comment] 2020-08-06 17:13
@emawby It doesn't work. If i use the XCFramework of the SDK i get this error:

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in NotificationService.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

This is my `Podfile`:

```
target 'MY_PROJECT_NAME' do

  pod 'FSPagerView'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'OneSignalXCFramework', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK.git', :tag => '2.15.1'

end

target 'OneSignalNotificationServiceExtension' do
  #only copy below line
  pod 'OneSignalXCFramework', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK.git', :tag => '2.15.1'
end
```

These are my Architectures for my_project target:
<img width="740" alt="Bildschirmfoto 2020-08-06 um 19 12 10" src="https://user-images.githubusercontent.com/42656134/89561426-c1c5c580-d818-11ea-8f3b-4cae62087564.png">

**Comment by rgomezp** [comment] 2020-08-06 22:31
Hello, please update to 2.15.3

**Comment by emawby** [comment] 2020-08-06 23:33
@SwiftiSwift Hello, this is a known Cocoapods bug that is fixed in their upcoming release (Cocoapods is only using one of the slices in the XCFramework). To get the fix now run `sudo gem install cocoapods --pre` and reinstall the XCFramework

**Comment by SwiftiSwift** [comment] 2020-08-07 07:46
@emawby Then i get this error: 

```
Multiple commands produce '/Users/USER_NAME/Library/Developer/Xcode/DerivedData/PROJECT_NAME-aeazewmhqxgqogghbnuwewuaajan/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignal':
1) That command depends on command in Target 'OneSignalXCFramework-iOS10.0' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'OneSignalXCFramework-iOS9.0' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
```

**Comment by emawby** [comment] 2020-10-15 23:21
> @emawby Then i get this error for 'MY_PROJECT Workspace':
> 
> ```
> Multiple commands produce '/Users/USER_NAME/Library/Developer/Xcode/DerivedData/PROJECT_NAME-aeazewmhqxgqogghbnuwewuaajan/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignal':
> 1) That command depends on command in Target 'OneSignalXCFramework-iOS10.0' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
> 2) That command depends on command in Target 'OneSignalXCFramework-iOS9.0' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
> ```
> 
> `pod deintegrate` and `pod install` doesn't work either

@SwiftiSwift are you still encountering this error with the latest version of Cocoapods? I am not able to reproduce this issue.

**Comment by SwiftiSwift** [comment] 2020-11-06 17:43
@emawby I still encounter this issue!

**Comment by emawby** [comment] 2020-11-24 19:27
@SwiftiSwift but are you on the latest version of cocoapods itself not the OneSignal pod?

**Comment by SwiftiSwift** [comment] 2020-11-24 19:29
Yes I ran `sudo gem install cocoapods --pre`

**Comment by emawby** [comment] 2020-11-24 19:40
What is your minimum deployment target? When I do this I do not have 2 targets in the `Pod` project I only have 1. Are you deploying to iOS 9?

**Comment by SwiftiSwift** [comment] 2020-12-08 18:38
My Minimum deployment target is iOS 9 for my project yes. For OneSignal it is iOS 10. These are my pods:
<img width="1385" alt="Bildschirmfoto 2020-12-08 um 19 37 53" src="https://user-images.githubusercontent.com/42656134/101526439-e8456a00-398c-11eb-8531-829119a83a22.png">

**Comment by SwiftiSwift** [comment] 2020-12-15 22:55
@emawby any update?

**Comment by emawby** [comment] 2021-08-05 23:48
@SwiftiSwift I apologize for missing this. If you are still having issues I recommend updating to the major release (3.0.0+) of the SDK and using the OneSignalXCFramework cocoapod

**Comment by SwiftiSwift** [comment] 2021-08-06 14:42
Updating to the latest version of 'OneSignalXCFramework' for Swift Package Manager fixed the issue

**Closed** 2021-08-19 22:51 UTC
Labels: Compatibility Issue, Bug: Not OneSignal
