### ISSUE TITLE
OneSignal.logoutEmail() is not removing user's e-mail

### ISSUE THREAD

**Issue by brunodelgado** [OneSignal/OneSignal-iOS-SDK#768] opened 2020-10-16 18:45 UTC
**Description:**
`OneSignal.logoutEmail()` is not removing user's e-mail.

**Environment**
Xcode 12.0.1
iOS 14
OneSignal via Cocoapods (2.15.13)

**Steps to Reproduce Issue:**

1. Add an e-mail to the current user using `OneSignal.setEmail("example@email.com")`
1. Check on OneSignal dashboard that the e-mail is set to the user.
1. Remove user's e-mail on logout calling `OneSignal.logoutEmail()`
1. Check on OneSignal dashboard that the e-mail was not removed

**Logs:**
I added OSEmailSubscriptionObserver and everything looks fine according to logs, but user's e-mail is not removed.

On `OneSignal.setEmail("example@email.com")`:
E-mail subscription state from: <OSEmailSubscriptionState: emailAddress: (null), emailUserId: (null)>
E-mail subscription state to: <OSEmailSubscriptionState: emailAddress: example@email.com, emailUserId: b0e4...>

On `OneSignal.logoutEmail()`:
E-mail subscription state from: <OSEmailSubscriptionState: emailAddress: example@email.com, emailUserId: b0e4...> 
E-mail subscription state to: <OSEmailSubscriptionState: emailAddress: (null), emailUserId: (null)>

But on OneSignal dashboard, user's e-mail is not removed.

**Comment by rgomezp** [comment] 2020-10-16 20:19
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1001

Duplicate of https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/239

**Comment by brunodelgado** [comment] 2020-10-19 17:58
I did the same step you did on OneSignal/react-native-onesignal#1001 but it doesn't remove the e-mail.
I'm subscribed on these two issue to keep me updated.

Thanks for now!

**Comment by rgomezp** [comment] 2020-11-13 23:50
Howdy @brunodelgado ,
Thanks for reporting this again.

This issue should now be resolved. Please let us know if you still encounter issues.

Enjoy!

**Closed by rgomezp** 2020-11-13 23:50 UTC
Labels: Possible Bug
